


-------------------------------------------------------------------------------------------
------------------------------------ Head, Cell & Content ---------------------------------
-------------------------------------     Category     ------------------------------------
-------------------------------------------------------------------------------------------



------------------------------------- Head Table Content -------------------------------------


INSERT INTO gfbio_head (headid, table_name, table_type)VALUES('1','gfbio_category','entity');


------------------------------------- Column Table Content -------------------------------------


INSERT INTO gfbio_column (columnid, headid, column_name)VALUES('1','1','id');				--gfbio_category
INSERT INTO gfbio_column (columnid, headid, column_name)VALUES('2','1','name');				--gfbio_category
INSERT INTO gfbio_column (columnid, headid, column_name)VALUES('3','1','label');			--gfbio_category
INSERT INTO gfbio_column (columnid, headid, column_name)VALUES('22','1','description');		--gfbio_category


------------------------------------- Content Table Content -------------------------------------


INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1','1','1','1','1');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('2','1','2','1','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('3','1','3','1','Africa');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1277','1','22','1','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('4','1','1','2','4');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('5','1','2','2','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('6','1','3','2','Algae');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1278','1','22','2','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('7','1','1','3','7');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('8','1','2','3','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('9','1','3','3','Amber collections');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1279','1','22','3','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('10','1','1','4','10');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('11','1','2','4','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('12','1','3','4','Antarctica');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1280','1','22','4','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('13','1','1','5','13');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('14','1','2','5','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('15','1','3','5','Anthropological collections');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1281','1','22','5','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('16','1','1','6','16');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('17','1','2','6','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('18','1','3','6','Arabic peninsula and adjacent areas');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1282','1','22','6','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('19','1','1','7','19');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('20','1','2','7','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('21','1','3','7','Arachnida');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1283','1','22','7','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('22','1','1','8','22');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('23','1','2','8','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('24','1','3','8','Arctica');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1284','1','22','8','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('25','1','1','9','25');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('26','1','2','9','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('27','1','3','9','Asia');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1285','1','22','9','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('28','1','1','10','28');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('29','1','2','10','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('30','1','3','10','Asterales');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1286','1','22','10','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('31','1','1','11','31');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('32','1','2','11','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('33','1','3','11','Aves');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1287','1','22','11','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('34','1','1','12','34');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('35','1','2','12','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('36','1','3','12','Bacteria and Archaea');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1288','1','22','12','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('37','1','1','13','37');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('38','1','2','13','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('39','1','3','13','Baden-Württemberg');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1289','1','22','13','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('40','1','1','14','40');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('41','1','2','14','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('42','1','3','14','Bavaria');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1290','1','22','14','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('43','1','1','15','43');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('44','1','2','15','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('45','1','3','15','Berlin');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1291','1','22','15','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('46','1','1','16','46');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('47','1','2','16','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('48','1','3','16','Biological environmental collections');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1292','1','22','16','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('49','1','1','17','49');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('50','1','2','17','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('51','1','3','17','Biological measurement data');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1293','1','22','17','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('52','1','1','18','52');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('53','1','2','18','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('54','1','3','18','Botanical collections');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1294','1','22','18','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('55','1','1','19','55');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('56','1','2','19','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('57','1','3','19','Brandenburg');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1295','1','22','19','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('58','1','1','20','58');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('59','1','2','20','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('60','1','3','20','Bryophyta');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1296','1','22','20','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('61','1','1','21','61');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('62','1','2','21','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('63','1','3','21','Caryophylales');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1297','1','22','21','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('64','1','1','22','64');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('65','1','2','22','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('66','1','3','22','Caucasus Region');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1298','1','22','22','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('67','1','1','23','67');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('68','1','2','23','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('69','1','3','23','Central Asia');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1299','1','22','23','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('70','1','1','24','70');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('71','1','2','24','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('72','1','3','24','Chelicerata');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1300','1','22','24','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('73','1','1','25','73');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('74','1','2','25','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('75','1','3','25','Collection data');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1301','1','22','25','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('76','1','1','26','76');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('77','1','2','26','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('78','1','3','26','Content based');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1302','1','22','26','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('79','1','1','27','79');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('80','1','2','27','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('81','1','3','27','Crustacea');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1303','1','22','27','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('82','1','1','28','82');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('83','1','2','28','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('84','1','3','28','Cuba and the Carribbean');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1304','1','22','28','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('85','1','1','29','85');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('86','1','2','29','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('87','1','3','29','Data producer notification on data publication');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1305','1','22','29','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('88','1','1','30','88');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('89','1','2','30','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('90','1','3','30','Deep sea fauna');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1306','1','22','30','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('91','1','1','31','91');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('92','1','2','31','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('93','1','3','31','Destruents');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1307','1','22','31','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('94','1','1','32','94');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('95','1','2','32','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('96','1','3','32','Diatoms');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1308','1','22','32','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('97','1','1','33','97');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('98','1','2','33','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('99','1','3','33','DNA-samples');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1309','1','22','33','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('103','1','1','35','103');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('104','1','2','35','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('105','1','3','35','Embargo period');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1310','1','22','35','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('106','1','1','36','106');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('107','1','2','36','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('108','1','3','36','Embargo until paper publication');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1311','1','22','36','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('109','1','1','37','109');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('110','1','2','37','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('111','1','3','37','Embryology');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1312','1','22','37','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('112','1','1','38','112');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('113','1','2','38','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('114','1','3','38','Environmental data');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1313','1','22','38','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('118','1','1','40','118');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('119','1','2','40','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('120','1','3','40','Europe');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1314','1','22','40','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('121','1','1','41','121');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('122','1','2','41','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('123','1','3','41','European Alps');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1315','1','22','41','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('124','1','1','42','124');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('125','1','2','42','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('126','1','3','42','Extreme regions worldwide (alpine, arid)');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1316','1','22','42','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('127','1','1','43','127');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('128','1','2','43','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('129','1','3','43','File type based');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1317','1','22','43','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('130','1','1','44','130');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('131','1','2','44','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('132','1','3','44','For publication only');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1318','1','22','44','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('133','1','1','45','133');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('134','1','2','45','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('135','1','3','45','Hemimetabola');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1319','1','22','45','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('136','1','1','46','136');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('137','1','2','46','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('138','1','3','46','Hesse');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1320','1','22','46','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('139','1','1','47','139');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('140','1','2','47','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('141','1','3','47','Indo-pacific');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1321','1','22','47','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('142','1','1','48','142');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('143','1','2','48','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('144','1','3','48','Insecta');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1322','1','22','48','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('145','1','1','49','145');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('146','1','2','49','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('147','1','3','49','Invertebrate fossils');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1323','1','22','49','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('148','1','1','50','148');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('149','1','2','50','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('150','1','3','50','Invertebrates');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1324','1','22','50','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('151','1','1','51','151');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('152','1','2','51','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('153','1','3','51','Japan');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1325','1','22','51','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('154','1','1','52','154');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('155','1','2','52','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('156','1','3','52','Lichen');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1326','1','22','52','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('157','1','1','53','157');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('158','1','2','53','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('159','1','3','53','Light microscopical slides');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1327','1','22','53','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('160','1','1','54','160');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('161','1','2','54','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('162','1','3','54','Limnological fauna');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1328','1','22','54','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('163','1','1','55','163');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('164','1','2','55','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('165','1','3','55','Littoral fauna');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1329','1','22','55','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('166','1','1','56','166');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('167','1','2','56','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('168','1','3','56','Macrofungi');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1330','1','22','56','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('169','1','1','57','169');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('170','1','2','57','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('171','1','3','57','Mammalia');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1331','1','22','57','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('172','1','1','58','172');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('173','1','2','58','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('174','1','3','58','Marine circumpolar fauna');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1332','1','22','58','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('175','1','1','59','175');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('176','1','2','59','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('177','1','3','59','Marine micro fauna');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1333','1','22','59','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('178','1','1','60','178');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('179','1','2','60','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('180','1','3','60','Mediterranean fauna');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1334','1','22','60','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('181','1','1','61','181');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('182','1','2','61','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('183','1','3','61','Mediterranean flora');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1335','1','22','61','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('184','1','1','62','184');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('185','1','2','62','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('186','1','3','62','Metazoa');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1336','1','22','62','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('187','1','1','63','187');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('188','1','2','63','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('189','1','3','63','Microfossils');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1337','1','22','63','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('190','1','1','64','190');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('191','1','2','64','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('192','1','3','64','Microfungi');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1338','1','22','64','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('193','1','1','65','193');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('194','1','2','65','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('195','1','3','65','Molecular data');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1339','1','22','65','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('196','1','1','66','196');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('197','1','2','66','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('198','1','3','66','Mollusca');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1340','1','22','66','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('199','1','1','67','199');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('200','1','2','67','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('201','1','3','67','Morphological and structural descriptions');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1341','1','22','67','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('202','1','1','68','202');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('203','1','2','68','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('204','1','3','68','Mycological collections');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1342','1','22','68','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('205','1','1','69','205');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('206','1','2','69','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('207','1','3','69','Myriapoda');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1343','1','22','69','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('208','1','1','70','208');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('209','1','2','70','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('210','1','3','70','North sea');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1344','1','22','70','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('211','1','1','71','211');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('212','1','2','71','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('213','1','3','71','Occurrence and observational data');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1345','1','22','71','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('214','1','1','72','214');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('215','1','2','72','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('216','1','3','72','Organisms');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1346','1','22','72','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('217','1','1','73','217');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('218','1','2','73','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('219','1','3','73','Palaeoanthropology');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1347','1','22','73','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('220','1','1','74','220');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('221','1','2','74','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('222','1','3','74','Paleontological collections');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1348','1','22','74','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('223','1','1','75','223');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('224','1','2','75','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('225','1','3','75','Parasitic fungi');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1349','1','22','75','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('226','1','1','76','226');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('227','1','2','76','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('228','1','3','76','Parasitic organisms');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1350','1','22','76','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('229','1','1','77','229');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('230','1','2','77','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('231','1','3','77','Plant fossils');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1351','1','22','77','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('232','1','1','78','232');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('233','1','2','78','Fishes');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('234','1','3','78','Pisces');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1352','1','22','78','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('235','1','1','79','235');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('236','1','2','79','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('237','1','3','79','Protozoa');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1353','1','22','79','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('238','1','1','80','238');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('239','1','2','80','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('240','1','3','80','Red sea');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1354','1','22','80','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('241','1','1','81','241');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('242','1','2','81','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('243','1','3','81','Registered GFBio users');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1355','1','22','81','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('244','1','1','82','244');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('245','1','2','82','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('246','1','3','82','Reptilia');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1356','1','22','82','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('247','1','1','83','247');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('248','1','2','83','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('249','1','3','83','Rhineland/North Rhine-Westphalia');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1357','1','22','83','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('250','1','1','84','250');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('251','1','2','84','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('252','1','3','84','Single users');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1358','1','22','84','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('253','1','1','85','253');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('254','1','2','85','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('255','1','3','85','Soil organisms');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1359','1','22','85','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('256','1','1','86','256');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('257','1','2','86','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('258','1','3','86','South and Central America');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1360','1','22','86','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('259','1','1','87','259');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('260','1','2','87','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('261','1','3','87','South Asia');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1361','1','22','87','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('262','1','1','88','262');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('263','1','2','88','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('264','1','3','88','Southeast Asia');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1362','1','22','88','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('265','1','1','89','265');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('266','1','2','89','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('267','1','3','89','Survey data');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1363','1','22','89','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('268','1','1','90','268');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('269','1','2','90','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('270','1','3','90','Terrestrial fauna');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1364','1','22','90','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('271','1','1','91','271');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('272','1','2','91','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('273','1','3','91','Tissue collection');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1365','1','22','1','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('274','1','1','92','274');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('275','1','2','92','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('276','1','3','92','Trait data');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1366','1','22','92','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('277','1','1','93','277');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('278','1','2','93','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('279','1','3','93','Tropical rainforest');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1367','1','22','93','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('280','1','1','94','280');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('281','1','2','94','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('282','1','3','94','Vascular plants');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1368','1','22','94','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('283','1','1','95','283');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('284','1','2','95','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('285','1','3','95','Vermes');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1369','1','22','95','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('286','1','1','96','286');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('287','1','2','96','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('288','1','3','96','Vertebrate fossils');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1370','1','22','96','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('289','1','1','97','289');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('290','1','2','97','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('291','1','3','97','Viruses and Phages');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1371','1','22','97','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('292','1','1','98','292');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('293','1','2','98','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('294','1','3','98','Workgroup members');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1372','1','22','98','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('295','1','1','99','295');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('296','1','2','99','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('297','1','3','99','Zoological collections');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1373','1','22','99','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('624','1','1','256','624');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('625','1','2','256','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('626','1','3','256','Cell cultures');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1374','1','22','256','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('695','1','1','291','695');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('696','1','2','291','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('697','1','3','291','Tissue cultures');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1375','1','22','291','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('716','1','1','301','716');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('717','1','2','301','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('718','1','3','301','Amphibia');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1376','1','22','301','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1087','1','1','486','1087');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1088','1','2','486','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1089','1','3','486','America');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1377','1','22','486','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1242','1','1','563','1242');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1243','1','2','563','');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1244','1','3','563','Vertebrata');
INSERT INTO gfbio_content (contentid, headid, columnid, rowid, cellcontent)VALUES('1378','1','22','563','');