/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.gfbio.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.gfbio.model.Column;
import org.gfbio.model.ColumnModel;
import org.gfbio.model.ColumnSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Column service. Represents a row in the &quot;gfbio_Column&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.gfbio.model.ColumnModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ColumnImpl}.
 * </p>
 *
 * @author Marcel Froemming
 * @see ColumnImpl
 * @see org.gfbio.model.Column
 * @see org.gfbio.model.ColumnModel
 * @generated
 */
@JSON(strict = true)
public class ColumnModelImpl extends BaseModelImpl<Column>
	implements ColumnModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a column model instance should use the {@link org.gfbio.model.Column} interface instead.
	 */
	public static final String TABLE_NAME = "gfbio_Column";
	public static final Object[][] TABLE_COLUMNS = {
			{ "columnID", Types.BIGINT },
			{ "headID", Types.BIGINT },
			{ "column_name", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table gfbio_Column (columnID LONG not null primary key,headID LONG,column_name VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table gfbio_Column";
	public static final String ORDER_BY_JPQL = " ORDER BY column.columnID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY gfbio_Column.columnID ASC";
	public static final String DATA_SOURCE = "gfbioDataSource";
	public static final String SESSION_FACTORY = "gfbioSessionFactory";
	public static final String TX_MANAGER = "gfbioTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.gfbio.model.Column"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.gfbio.model.Column"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.gfbio.model.Column"),
			true);
	public static long COLUMNID_COLUMN_BITMASK = 1L;
	public static long COLUMN_NAME_COLUMN_BITMASK = 2L;
	public static long HEADID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Column toModel(ColumnSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Column model = new ColumnImpl();

		model.setColumnID(soapModel.getColumnID());
		model.setHeadID(soapModel.getHeadID());
		model.setColumn_name(soapModel.getColumn_name());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Column> toModels(ColumnSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Column> models = new ArrayList<Column>(soapModels.length);

		for (ColumnSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.gfbio.model.Column"));

	public ColumnModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _columnID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setColumnID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _columnID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Column.class;
	}

	@Override
	public String getModelClassName() {
		return Column.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("columnID", getColumnID());
		attributes.put("headID", getHeadID());
		attributes.put("column_name", getColumn_name());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long columnID = (Long)attributes.get("columnID");

		if (columnID != null) {
			setColumnID(columnID);
		}

		Long headID = (Long)attributes.get("headID");

		if (headID != null) {
			setHeadID(headID);
		}

		String column_name = (String)attributes.get("column_name");

		if (column_name != null) {
			setColumn_name(column_name);
		}
	}

	@JSON
	@Override
	public long getColumnID() {
		return _columnID;
	}

	@Override
	public void setColumnID(long columnID) {
		_columnBitmask = -1L;

		if (!_setOriginalColumnID) {
			_setOriginalColumnID = true;

			_originalColumnID = _columnID;
		}

		_columnID = columnID;
	}

	public long getOriginalColumnID() {
		return _originalColumnID;
	}

	@JSON
	@Override
	public long getHeadID() {
		return _headID;
	}

	@Override
	public void setHeadID(long headID) {
		_columnBitmask |= HEADID_COLUMN_BITMASK;

		if (!_setOriginalHeadID) {
			_setOriginalHeadID = true;

			_originalHeadID = _headID;
		}

		_headID = headID;
	}

	public long getOriginalHeadID() {
		return _originalHeadID;
	}

	@JSON
	@Override
	public String getColumn_name() {
		if (_column_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _column_name;
		}
	}

	@Override
	public void setColumn_name(String column_name) {
		_columnBitmask |= COLUMN_NAME_COLUMN_BITMASK;

		if (_originalColumn_name == null) {
			_originalColumn_name = _column_name;
		}

		_column_name = column_name;
	}

	public String getOriginalColumn_name() {
		return GetterUtil.getString(_originalColumn_name);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Column.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Column toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Column)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ColumnImpl columnImpl = new ColumnImpl();

		columnImpl.setColumnID(getColumnID());
		columnImpl.setHeadID(getHeadID());
		columnImpl.setColumn_name(getColumn_name());

		columnImpl.resetOriginalValues();

		return columnImpl;
	}

	@Override
	public int compareTo(Column column) {
		int value = 0;

		if (getColumnID() < column.getColumnID()) {
			value = -1;
		}
		else if (getColumnID() > column.getColumnID()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Column)) {
			return false;
		}

		Column column = (Column)obj;

		long primaryKey = column.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ColumnModelImpl columnModelImpl = this;

		columnModelImpl._originalColumnID = columnModelImpl._columnID;

		columnModelImpl._setOriginalColumnID = false;

		columnModelImpl._originalHeadID = columnModelImpl._headID;

		columnModelImpl._setOriginalHeadID = false;

		columnModelImpl._originalColumn_name = columnModelImpl._column_name;

		columnModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Column> toCacheModel() {
		ColumnCacheModel columnCacheModel = new ColumnCacheModel();

		columnCacheModel.columnID = getColumnID();

		columnCacheModel.headID = getHeadID();

		columnCacheModel.column_name = getColumn_name();

		String column_name = columnCacheModel.column_name;

		if ((column_name != null) && (column_name.length() == 0)) {
			columnCacheModel.column_name = null;
		}

		return columnCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{columnID=");
		sb.append(getColumnID());
		sb.append(", headID=");
		sb.append(getHeadID());
		sb.append(", column_name=");
		sb.append(getColumn_name());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("org.gfbio.model.Column");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>columnID</column-name><column-value><![CDATA[");
		sb.append(getColumnID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>headID</column-name><column-value><![CDATA[");
		sb.append(getHeadID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>column_name</column-name><column-value><![CDATA[");
		sb.append(getColumn_name());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Column.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { Column.class };
	private long _columnID;
	private long _originalColumnID;
	private boolean _setOriginalColumnID;
	private long _headID;
	private long _originalHeadID;
	private boolean _setOriginalHeadID;
	private String _column_name;
	private String _originalColumn_name;
	private long _columnBitmask;
	private Column _escapedModel;
}