/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.gfbio.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.gfbio.model.Basket_User;
import org.gfbio.model.Basket_UserModel;
import org.gfbio.model.Basket_UserSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Basket_User service. Represents a row in the &quot;gfbio_Basket_User&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.gfbio.model.Basket_UserModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Basket_UserImpl}.
 * </p>
 *
 * @author Felicitas Loeffler
 * @see Basket_UserImpl
 * @see org.gfbio.model.Basket_User
 * @see org.gfbio.model.Basket_UserModel
 * @generated
 */
@JSON(strict = true)
public class Basket_UserModelImpl extends BaseModelImpl<Basket_User>
	implements Basket_UserModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a basket_ user model instance should use the {@link org.gfbio.model.Basket_User} interface instead.
	 */
	public static final String TABLE_NAME = "gfbio_Basket_User";
	public static final Object[][] TABLE_COLUMNS = {
			{ "basketID", Types.BIGINT },
			{ "userID", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "basketJSON", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table gfbio_Basket_User (basketID LONG not null primary key,userID LONG,name VARCHAR(75) null,basketJSON VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table gfbio_Basket_User";
	public static final String ORDER_BY_JPQL = " ORDER BY basket_User.basketID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY gfbio_Basket_User.basketID ASC";
	public static final String DATA_SOURCE = "gfbioDataSource";
	public static final String SESSION_FACTORY = "gfbioSessionFactory";
	public static final String TX_MANAGER = "gfbioTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.gfbio.model.Basket_User"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.gfbio.model.Basket_User"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.gfbio.model.Basket_User"),
			true);
	public static long BASKETID_COLUMN_BITMASK = 1L;
	public static long USERID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Basket_User toModel(Basket_UserSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Basket_User model = new Basket_UserImpl();

		model.setBasketID(soapModel.getBasketID());
		model.setUserID(soapModel.getUserID());
		model.setName(soapModel.getName());
		model.setBasketJSON(soapModel.getBasketJSON());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Basket_User> toModels(Basket_UserSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Basket_User> models = new ArrayList<Basket_User>(soapModels.length);

		for (Basket_UserSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.gfbio.model.Basket_User"));

	public Basket_UserModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _basketID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBasketID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _basketID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Basket_User.class;
	}

	@Override
	public String getModelClassName() {
		return Basket_User.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("basketID", getBasketID());
		attributes.put("userID", getUserID());
		attributes.put("name", getName());
		attributes.put("basketJSON", getBasketJSON());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long basketID = (Long)attributes.get("basketID");

		if (basketID != null) {
			setBasketID(basketID);
		}

		Long userID = (Long)attributes.get("userID");

		if (userID != null) {
			setUserID(userID);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String basketJSON = (String)attributes.get("basketJSON");

		if (basketJSON != null) {
			setBasketJSON(basketJSON);
		}
	}

	@JSON
	@Override
	public long getBasketID() {
		return _basketID;
	}

	@Override
	public void setBasketID(long basketID) {
		_columnBitmask |= BASKETID_COLUMN_BITMASK;

		if (!_setOriginalBasketID) {
			_setOriginalBasketID = true;

			_originalBasketID = _basketID;
		}

		_basketID = basketID;
	}

	public long getOriginalBasketID() {
		return _originalBasketID;
	}

	@JSON
	@Override
	public long getUserID() {
		return _userID;
	}

	@Override
	public void setUserID(long userID) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserID) {
			_setOriginalUserID = true;

			_originalUserID = _userID;
		}

		_userID = userID;
	}

	public long getOriginalUserID() {
		return _originalUserID;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public String getBasketJSON() {
		if (_basketJSON == null) {
			return StringPool.BLANK;
		}
		else {
			return _basketJSON;
		}
	}

	@Override
	public void setBasketJSON(String basketJSON) {
		_basketJSON = basketJSON;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Basket_User.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Basket_User toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Basket_User)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		Basket_UserImpl basket_UserImpl = new Basket_UserImpl();

		basket_UserImpl.setBasketID(getBasketID());
		basket_UserImpl.setUserID(getUserID());
		basket_UserImpl.setName(getName());
		basket_UserImpl.setBasketJSON(getBasketJSON());

		basket_UserImpl.resetOriginalValues();

		return basket_UserImpl;
	}

	@Override
	public int compareTo(Basket_User basket_User) {
		long primaryKey = basket_User.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Basket_User)) {
			return false;
		}

		Basket_User basket_User = (Basket_User)obj;

		long primaryKey = basket_User.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		Basket_UserModelImpl basket_UserModelImpl = this;

		basket_UserModelImpl._originalBasketID = basket_UserModelImpl._basketID;

		basket_UserModelImpl._setOriginalBasketID = false;

		basket_UserModelImpl._originalUserID = basket_UserModelImpl._userID;

		basket_UserModelImpl._setOriginalUserID = false;

		basket_UserModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Basket_User> toCacheModel() {
		Basket_UserCacheModel basket_UserCacheModel = new Basket_UserCacheModel();

		basket_UserCacheModel.basketID = getBasketID();

		basket_UserCacheModel.userID = getUserID();

		basket_UserCacheModel.name = getName();

		String name = basket_UserCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			basket_UserCacheModel.name = null;
		}

		basket_UserCacheModel.basketJSON = getBasketJSON();

		String basketJSON = basket_UserCacheModel.basketJSON;

		if ((basketJSON != null) && (basketJSON.length() == 0)) {
			basket_UserCacheModel.basketJSON = null;
		}

		return basket_UserCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{basketID=");
		sb.append(getBasketID());
		sb.append(", userID=");
		sb.append(getUserID());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", basketJSON=");
		sb.append(getBasketJSON());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("org.gfbio.model.Basket_User");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>basketID</column-name><column-value><![CDATA[");
		sb.append(getBasketID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userID</column-name><column-value><![CDATA[");
		sb.append(getUserID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>basketJSON</column-name><column-value><![CDATA[");
		sb.append(getBasketJSON());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Basket_User.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Basket_User.class
		};
	private long _basketID;
	private long _originalBasketID;
	private boolean _setOriginalBasketID;
	private long _userID;
	private long _originalUserID;
	private boolean _setOriginalUserID;
	private String _name;
	private String _basketJSON;
	private long _columnBitmask;
	private Basket_User _escapedModel;
}