/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.gfbio.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.gfbio.model.Cell;
import org.gfbio.model.CellModel;
import org.gfbio.model.CellSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Cell service. Represents a row in the &quot;gfbio_Cell&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.gfbio.model.CellModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CellImpl}.
 * </p>
 *
 * @author Marcel Froemming
 * @see CellImpl
 * @see org.gfbio.model.Cell
 * @see org.gfbio.model.CellModel
 * @generated
 */
@JSON(strict = true)
public class CellModelImpl extends BaseModelImpl<Cell> implements CellModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cell model instance should use the {@link org.gfbio.model.Cell} interface instead.
	 */
	public static final String TABLE_NAME = "gfbio_Cell";
	public static final Object[][] TABLE_COLUMNS = {
			{ "cellID", Types.BIGINT },
			{ "content", Types.VARCHAR },
			{ "task", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table gfbio_Cell (cellID LONG not null primary key,content VARCHAR(75) null,task VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table gfbio_Cell";
	public static final String ORDER_BY_JPQL = " ORDER BY cell.content ASC";
	public static final String ORDER_BY_SQL = " ORDER BY gfbio_Cell.content ASC";
	public static final String DATA_SOURCE = "gfbioDataSource";
	public static final String SESSION_FACTORY = "gfbioSessionFactory";
	public static final String TX_MANAGER = "gfbioTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.gfbio.model.Cell"), false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.gfbio.model.Cell"), false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.gfbio.model.Cell"),
			true);
	public static long CELLID_COLUMN_BITMASK = 1L;
	public static long CONTENT_COLUMN_BITMASK = 2L;
	public static long TASK_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Cell toModel(CellSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Cell model = new CellImpl();

		model.setCellID(soapModel.getCellID());
		model.setContent(soapModel.getContent());
		model.setTask(soapModel.getTask());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Cell> toModels(CellSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Cell> models = new ArrayList<Cell>(soapModels.length);

		for (CellSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.gfbio.model.Cell"));

	public CellModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _cellID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCellID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _cellID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Cell.class;
	}

	@Override
	public String getModelClassName() {
		return Cell.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("cellID", getCellID());
		attributes.put("content", getContent());
		attributes.put("task", getTask());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long cellID = (Long)attributes.get("cellID");

		if (cellID != null) {
			setCellID(cellID);
		}

		String content = (String)attributes.get("content");

		if (content != null) {
			setContent(content);
		}

		String task = (String)attributes.get("task");

		if (task != null) {
			setTask(task);
		}
	}

	@JSON
	@Override
	public long getCellID() {
		return _cellID;
	}

	@Override
	public void setCellID(long cellID) {
		_columnBitmask |= CELLID_COLUMN_BITMASK;

		if (!_setOriginalCellID) {
			_setOriginalCellID = true;

			_originalCellID = _cellID;
		}

		_cellID = cellID;
	}

	public long getOriginalCellID() {
		return _originalCellID;
	}

	@JSON
	@Override
	public String getContent() {
		if (_content == null) {
			return StringPool.BLANK;
		}
		else {
			return _content;
		}
	}

	@Override
	public void setContent(String content) {
		_columnBitmask = -1L;

		if (_originalContent == null) {
			_originalContent = _content;
		}

		_content = content;
	}

	public String getOriginalContent() {
		return GetterUtil.getString(_originalContent);
	}

	@JSON
	@Override
	public String getTask() {
		if (_task == null) {
			return StringPool.BLANK;
		}
		else {
			return _task;
		}
	}

	@Override
	public void setTask(String task) {
		_columnBitmask |= TASK_COLUMN_BITMASK;

		if (_originalTask == null) {
			_originalTask = _task;
		}

		_task = task;
	}

	public String getOriginalTask() {
		return GetterUtil.getString(_originalTask);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Cell.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Cell toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Cell)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CellImpl cellImpl = new CellImpl();

		cellImpl.setCellID(getCellID());
		cellImpl.setContent(getContent());
		cellImpl.setTask(getTask());

		cellImpl.resetOriginalValues();

		return cellImpl;
	}

	@Override
	public int compareTo(Cell cell) {
		int value = 0;

		value = getContent().compareTo(cell.getContent());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Cell)) {
			return false;
		}

		Cell cell = (Cell)obj;

		long primaryKey = cell.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CellModelImpl cellModelImpl = this;

		cellModelImpl._originalCellID = cellModelImpl._cellID;

		cellModelImpl._setOriginalCellID = false;

		cellModelImpl._originalContent = cellModelImpl._content;

		cellModelImpl._originalTask = cellModelImpl._task;

		cellModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Cell> toCacheModel() {
		CellCacheModel cellCacheModel = new CellCacheModel();

		cellCacheModel.cellID = getCellID();

		cellCacheModel.content = getContent();

		String content = cellCacheModel.content;

		if ((content != null) && (content.length() == 0)) {
			cellCacheModel.content = null;
		}

		cellCacheModel.task = getTask();

		String task = cellCacheModel.task;

		if ((task != null) && (task.length() == 0)) {
			cellCacheModel.task = null;
		}

		return cellCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{cellID=");
		sb.append(getCellID());
		sb.append(", content=");
		sb.append(getContent());
		sb.append(", task=");
		sb.append(getTask());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("org.gfbio.model.Cell");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>cellID</column-name><column-value><![CDATA[");
		sb.append(getCellID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>content</column-name><column-value><![CDATA[");
		sb.append(getContent());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>task</column-name><column-value><![CDATA[");
		sb.append(getTask());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Cell.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { Cell.class };
	private long _cellID;
	private long _originalCellID;
	private boolean _setOriginalCellID;
	private String _content;
	private String _originalContent;
	private String _task;
	private String _originalTask;
	private long _columnBitmask;
	private Cell _escapedModel;
}