/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.gfbio.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import org.gfbio.model.Head;

import org.gfbio.service.HeadLocalServiceUtil;

/**
 * The extended model base implementation for the Head service. Represents a row in the &quot;gfbio_Head&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HeadImpl}.
 * </p>
 *
 * @author Marcel Froemming
 * @see HeadImpl
 * @see org.gfbio.model.Head
 * @generated
 */
public abstract class HeadBaseImpl extends HeadModelImpl implements Head {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a head model instance should use the {@link Head} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			HeadLocalServiceUtil.addHead(this);
		}
		else {
			HeadLocalServiceUtil.updateHead(this);
		}
	}
}