/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.gfbio.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.gfbio.model.Position;
import org.gfbio.model.PositionModel;
import org.gfbio.model.PositionSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Position service. Represents a row in the &quot;gfbio_Position&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.gfbio.model.PositionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PositionImpl}.
 * </p>
 *
 * @author Felicitas Loeffler
 * @see PositionImpl
 * @see org.gfbio.model.Position
 * @see org.gfbio.model.PositionModel
 * @generated
 */
@JSON(strict = true)
public class PositionModelImpl extends BaseModelImpl<Position>
	implements PositionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a position model instance should use the {@link org.gfbio.model.Position} interface instead.
	 */
	public static final String TABLE_NAME = "gfbio_Position";
	public static final Object[][] TABLE_COLUMNS = {
			{ "positionID", Types.BIGINT },
			{ "headID", Types.BIGINT },
			{ "column01", Types.VARCHAR },
			{ "column02", Types.VARCHAR },
			{ "column03", Types.VARCHAR },
			{ "column04", Types.VARCHAR },
			{ "column05", Types.VARCHAR },
			{ "column06", Types.VARCHAR },
			{ "column07", Types.VARCHAR },
			{ "column08", Types.VARCHAR },
			{ "column09", Types.VARCHAR },
			{ "column10", Types.VARCHAR },
			{ "column11", Types.VARCHAR },
			{ "column12", Types.VARCHAR },
			{ "column13", Types.VARCHAR },
			{ "column14", Types.VARCHAR },
			{ "column15", Types.VARCHAR },
			{ "column16", Types.VARCHAR },
			{ "column17", Types.VARCHAR },
			{ "column18", Types.VARCHAR },
			{ "column19", Types.VARCHAR },
			{ "column20", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table gfbio_Position (positionID LONG not null primary key,headID LONG,column01 VARCHAR(75) null,column02 VARCHAR(75) null,column03 VARCHAR(75) null,column04 VARCHAR(75) null,column05 VARCHAR(75) null,column06 VARCHAR(75) null,column07 VARCHAR(75) null,column08 VARCHAR(75) null,column09 VARCHAR(75) null,column10 VARCHAR(75) null,column11 VARCHAR(75) null,column12 VARCHAR(75) null,column13 VARCHAR(75) null,column14 VARCHAR(75) null,column15 VARCHAR(75) null,column16 VARCHAR(75) null,column17 VARCHAR(75) null,column18 VARCHAR(75) null,column19 VARCHAR(75) null,column20 VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table gfbio_Position";
	public static final String ORDER_BY_JPQL = " ORDER BY position.positionID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY gfbio_Position.positionID ASC";
	public static final String DATA_SOURCE = "gfbioDataSource";
	public static final String SESSION_FACTORY = "gfbioSessionFactory";
	public static final String TX_MANAGER = "gfbioTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.gfbio.model.Position"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.gfbio.model.Position"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.gfbio.model.Position"),
			true);
	public static long HEADID_COLUMN_BITMASK = 1L;
	public static long POSITIONID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Position toModel(PositionSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Position model = new PositionImpl();

		model.setPositionID(soapModel.getPositionID());
		model.setHeadID(soapModel.getHeadID());
		model.setColumn01(soapModel.getColumn01());
		model.setColumn02(soapModel.getColumn02());
		model.setColumn03(soapModel.getColumn03());
		model.setColumn04(soapModel.getColumn04());
		model.setColumn05(soapModel.getColumn05());
		model.setColumn06(soapModel.getColumn06());
		model.setColumn07(soapModel.getColumn07());
		model.setColumn08(soapModel.getColumn08());
		model.setColumn09(soapModel.getColumn09());
		model.setColumn10(soapModel.getColumn10());
		model.setColumn11(soapModel.getColumn11());
		model.setColumn12(soapModel.getColumn12());
		model.setColumn13(soapModel.getColumn13());
		model.setColumn14(soapModel.getColumn14());
		model.setColumn15(soapModel.getColumn15());
		model.setColumn16(soapModel.getColumn16());
		model.setColumn17(soapModel.getColumn17());
		model.setColumn18(soapModel.getColumn18());
		model.setColumn19(soapModel.getColumn19());
		model.setColumn20(soapModel.getColumn20());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Position> toModels(PositionSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Position> models = new ArrayList<Position>(soapModels.length);

		for (PositionSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.gfbio.model.Position"));

	public PositionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _positionID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPositionID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _positionID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Position.class;
	}

	@Override
	public String getModelClassName() {
		return Position.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("positionID", getPositionID());
		attributes.put("headID", getHeadID());
		attributes.put("column01", getColumn01());
		attributes.put("column02", getColumn02());
		attributes.put("column03", getColumn03());
		attributes.put("column04", getColumn04());
		attributes.put("column05", getColumn05());
		attributes.put("column06", getColumn06());
		attributes.put("column07", getColumn07());
		attributes.put("column08", getColumn08());
		attributes.put("column09", getColumn09());
		attributes.put("column10", getColumn10());
		attributes.put("column11", getColumn11());
		attributes.put("column12", getColumn12());
		attributes.put("column13", getColumn13());
		attributes.put("column14", getColumn14());
		attributes.put("column15", getColumn15());
		attributes.put("column16", getColumn16());
		attributes.put("column17", getColumn17());
		attributes.put("column18", getColumn18());
		attributes.put("column19", getColumn19());
		attributes.put("column20", getColumn20());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long positionID = (Long)attributes.get("positionID");

		if (positionID != null) {
			setPositionID(positionID);
		}

		Long headID = (Long)attributes.get("headID");

		if (headID != null) {
			setHeadID(headID);
		}

		String column01 = (String)attributes.get("column01");

		if (column01 != null) {
			setColumn01(column01);
		}

		String column02 = (String)attributes.get("column02");

		if (column02 != null) {
			setColumn02(column02);
		}

		String column03 = (String)attributes.get("column03");

		if (column03 != null) {
			setColumn03(column03);
		}

		String column04 = (String)attributes.get("column04");

		if (column04 != null) {
			setColumn04(column04);
		}

		String column05 = (String)attributes.get("column05");

		if (column05 != null) {
			setColumn05(column05);
		}

		String column06 = (String)attributes.get("column06");

		if (column06 != null) {
			setColumn06(column06);
		}

		String column07 = (String)attributes.get("column07");

		if (column07 != null) {
			setColumn07(column07);
		}

		String column08 = (String)attributes.get("column08");

		if (column08 != null) {
			setColumn08(column08);
		}

		String column09 = (String)attributes.get("column09");

		if (column09 != null) {
			setColumn09(column09);
		}

		String column10 = (String)attributes.get("column10");

		if (column10 != null) {
			setColumn10(column10);
		}

		String column11 = (String)attributes.get("column11");

		if (column11 != null) {
			setColumn11(column11);
		}

		String column12 = (String)attributes.get("column12");

		if (column12 != null) {
			setColumn12(column12);
		}

		String column13 = (String)attributes.get("column13");

		if (column13 != null) {
			setColumn13(column13);
		}

		String column14 = (String)attributes.get("column14");

		if (column14 != null) {
			setColumn14(column14);
		}

		String column15 = (String)attributes.get("column15");

		if (column15 != null) {
			setColumn15(column15);
		}

		String column16 = (String)attributes.get("column16");

		if (column16 != null) {
			setColumn16(column16);
		}

		String column17 = (String)attributes.get("column17");

		if (column17 != null) {
			setColumn17(column17);
		}

		String column18 = (String)attributes.get("column18");

		if (column18 != null) {
			setColumn18(column18);
		}

		String column19 = (String)attributes.get("column19");

		if (column19 != null) {
			setColumn19(column19);
		}

		String column20 = (String)attributes.get("column20");

		if (column20 != null) {
			setColumn20(column20);
		}
	}

	@JSON
	@Override
	public long getPositionID() {
		return _positionID;
	}

	@Override
	public void setPositionID(long positionID) {
		_columnBitmask = -1L;

		if (!_setOriginalPositionID) {
			_setOriginalPositionID = true;

			_originalPositionID = _positionID;
		}

		_positionID = positionID;
	}

	public long getOriginalPositionID() {
		return _originalPositionID;
	}

	@JSON
	@Override
	public long getHeadID() {
		return _headID;
	}

	@Override
	public void setHeadID(long headID) {
		_columnBitmask |= HEADID_COLUMN_BITMASK;

		if (!_setOriginalHeadID) {
			_setOriginalHeadID = true;

			_originalHeadID = _headID;
		}

		_headID = headID;
	}

	public long getOriginalHeadID() {
		return _originalHeadID;
	}

	@JSON
	@Override
	public String getColumn01() {
		if (_column01 == null) {
			return StringPool.BLANK;
		}
		else {
			return _column01;
		}
	}

	@Override
	public void setColumn01(String column01) {
		_column01 = column01;
	}

	@JSON
	@Override
	public String getColumn02() {
		if (_column02 == null) {
			return StringPool.BLANK;
		}
		else {
			return _column02;
		}
	}

	@Override
	public void setColumn02(String column02) {
		_column02 = column02;
	}

	@JSON
	@Override
	public String getColumn03() {
		if (_column03 == null) {
			return StringPool.BLANK;
		}
		else {
			return _column03;
		}
	}

	@Override
	public void setColumn03(String column03) {
		_column03 = column03;
	}

	@JSON
	@Override
	public String getColumn04() {
		if (_column04 == null) {
			return StringPool.BLANK;
		}
		else {
			return _column04;
		}
	}

	@Override
	public void setColumn04(String column04) {
		_column04 = column04;
	}

	@JSON
	@Override
	public String getColumn05() {
		if (_column05 == null) {
			return StringPool.BLANK;
		}
		else {
			return _column05;
		}
	}

	@Override
	public void setColumn05(String column05) {
		_column05 = column05;
	}

	@JSON
	@Override
	public String getColumn06() {
		if (_column06 == null) {
			return StringPool.BLANK;
		}
		else {
			return _column06;
		}
	}

	@Override
	public void setColumn06(String column06) {
		_column06 = column06;
	}

	@JSON
	@Override
	public String getColumn07() {
		if (_column07 == null) {
			return StringPool.BLANK;
		}
		else {
			return _column07;
		}
	}

	@Override
	public void setColumn07(String column07) {
		_column07 = column07;
	}

	@JSON
	@Override
	public String getColumn08() {
		if (_column08 == null) {
			return StringPool.BLANK;
		}
		else {
			return _column08;
		}
	}

	@Override
	public void setColumn08(String column08) {
		_column08 = column08;
	}

	@JSON
	@Override
	public String getColumn09() {
		if (_column09 == null) {
			return StringPool.BLANK;
		}
		else {
			return _column09;
		}
	}

	@Override
	public void setColumn09(String column09) {
		_column09 = column09;
	}

	@JSON
	@Override
	public String getColumn10() {
		if (_column10 == null) {
			return StringPool.BLANK;
		}
		else {
			return _column10;
		}
	}

	@Override
	public void setColumn10(String column10) {
		_column10 = column10;
	}

	@JSON
	@Override
	public String getColumn11() {
		if (_column11 == null) {
			return StringPool.BLANK;
		}
		else {
			return _column11;
		}
	}

	@Override
	public void setColumn11(String column11) {
		_column11 = column11;
	}

	@JSON
	@Override
	public String getColumn12() {
		if (_column12 == null) {
			return StringPool.BLANK;
		}
		else {
			return _column12;
		}
	}

	@Override
	public void setColumn12(String column12) {
		_column12 = column12;
	}

	@JSON
	@Override
	public String getColumn13() {
		if (_column13 == null) {
			return StringPool.BLANK;
		}
		else {
			return _column13;
		}
	}

	@Override
	public void setColumn13(String column13) {
		_column13 = column13;
	}

	@JSON
	@Override
	public String getColumn14() {
		if (_column14 == null) {
			return StringPool.BLANK;
		}
		else {
			return _column14;
		}
	}

	@Override
	public void setColumn14(String column14) {
		_column14 = column14;
	}

	@JSON
	@Override
	public String getColumn15() {
		if (_column15 == null) {
			return StringPool.BLANK;
		}
		else {
			return _column15;
		}
	}

	@Override
	public void setColumn15(String column15) {
		_column15 = column15;
	}

	@JSON
	@Override
	public String getColumn16() {
		if (_column16 == null) {
			return StringPool.BLANK;
		}
		else {
			return _column16;
		}
	}

	@Override
	public void setColumn16(String column16) {
		_column16 = column16;
	}

	@JSON
	@Override
	public String getColumn17() {
		if (_column17 == null) {
			return StringPool.BLANK;
		}
		else {
			return _column17;
		}
	}

	@Override
	public void setColumn17(String column17) {
		_column17 = column17;
	}

	@JSON
	@Override
	public String getColumn18() {
		if (_column18 == null) {
			return StringPool.BLANK;
		}
		else {
			return _column18;
		}
	}

	@Override
	public void setColumn18(String column18) {
		_column18 = column18;
	}

	@JSON
	@Override
	public String getColumn19() {
		if (_column19 == null) {
			return StringPool.BLANK;
		}
		else {
			return _column19;
		}
	}

	@Override
	public void setColumn19(String column19) {
		_column19 = column19;
	}

	@JSON
	@Override
	public String getColumn20() {
		if (_column20 == null) {
			return StringPool.BLANK;
		}
		else {
			return _column20;
		}
	}

	@Override
	public void setColumn20(String column20) {
		_column20 = column20;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Position.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Position toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Position)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PositionImpl positionImpl = new PositionImpl();

		positionImpl.setPositionID(getPositionID());
		positionImpl.setHeadID(getHeadID());
		positionImpl.setColumn01(getColumn01());
		positionImpl.setColumn02(getColumn02());
		positionImpl.setColumn03(getColumn03());
		positionImpl.setColumn04(getColumn04());
		positionImpl.setColumn05(getColumn05());
		positionImpl.setColumn06(getColumn06());
		positionImpl.setColumn07(getColumn07());
		positionImpl.setColumn08(getColumn08());
		positionImpl.setColumn09(getColumn09());
		positionImpl.setColumn10(getColumn10());
		positionImpl.setColumn11(getColumn11());
		positionImpl.setColumn12(getColumn12());
		positionImpl.setColumn13(getColumn13());
		positionImpl.setColumn14(getColumn14());
		positionImpl.setColumn15(getColumn15());
		positionImpl.setColumn16(getColumn16());
		positionImpl.setColumn17(getColumn17());
		positionImpl.setColumn18(getColumn18());
		positionImpl.setColumn19(getColumn19());
		positionImpl.setColumn20(getColumn20());

		positionImpl.resetOriginalValues();

		return positionImpl;
	}

	@Override
	public int compareTo(Position position) {
		int value = 0;

		if (getPositionID() < position.getPositionID()) {
			value = -1;
		}
		else if (getPositionID() > position.getPositionID()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Position)) {
			return false;
		}

		Position position = (Position)obj;

		long primaryKey = position.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		PositionModelImpl positionModelImpl = this;

		positionModelImpl._originalPositionID = positionModelImpl._positionID;

		positionModelImpl._setOriginalPositionID = false;

		positionModelImpl._originalHeadID = positionModelImpl._headID;

		positionModelImpl._setOriginalHeadID = false;

		positionModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Position> toCacheModel() {
		PositionCacheModel positionCacheModel = new PositionCacheModel();

		positionCacheModel.positionID = getPositionID();

		positionCacheModel.headID = getHeadID();

		positionCacheModel.column01 = getColumn01();

		String column01 = positionCacheModel.column01;

		if ((column01 != null) && (column01.length() == 0)) {
			positionCacheModel.column01 = null;
		}

		positionCacheModel.column02 = getColumn02();

		String column02 = positionCacheModel.column02;

		if ((column02 != null) && (column02.length() == 0)) {
			positionCacheModel.column02 = null;
		}

		positionCacheModel.column03 = getColumn03();

		String column03 = positionCacheModel.column03;

		if ((column03 != null) && (column03.length() == 0)) {
			positionCacheModel.column03 = null;
		}

		positionCacheModel.column04 = getColumn04();

		String column04 = positionCacheModel.column04;

		if ((column04 != null) && (column04.length() == 0)) {
			positionCacheModel.column04 = null;
		}

		positionCacheModel.column05 = getColumn05();

		String column05 = positionCacheModel.column05;

		if ((column05 != null) && (column05.length() == 0)) {
			positionCacheModel.column05 = null;
		}

		positionCacheModel.column06 = getColumn06();

		String column06 = positionCacheModel.column06;

		if ((column06 != null) && (column06.length() == 0)) {
			positionCacheModel.column06 = null;
		}

		positionCacheModel.column07 = getColumn07();

		String column07 = positionCacheModel.column07;

		if ((column07 != null) && (column07.length() == 0)) {
			positionCacheModel.column07 = null;
		}

		positionCacheModel.column08 = getColumn08();

		String column08 = positionCacheModel.column08;

		if ((column08 != null) && (column08.length() == 0)) {
			positionCacheModel.column08 = null;
		}

		positionCacheModel.column09 = getColumn09();

		String column09 = positionCacheModel.column09;

		if ((column09 != null) && (column09.length() == 0)) {
			positionCacheModel.column09 = null;
		}

		positionCacheModel.column10 = getColumn10();

		String column10 = positionCacheModel.column10;

		if ((column10 != null) && (column10.length() == 0)) {
			positionCacheModel.column10 = null;
		}

		positionCacheModel.column11 = getColumn11();

		String column11 = positionCacheModel.column11;

		if ((column11 != null) && (column11.length() == 0)) {
			positionCacheModel.column11 = null;
		}

		positionCacheModel.column12 = getColumn12();

		String column12 = positionCacheModel.column12;

		if ((column12 != null) && (column12.length() == 0)) {
			positionCacheModel.column12 = null;
		}

		positionCacheModel.column13 = getColumn13();

		String column13 = positionCacheModel.column13;

		if ((column13 != null) && (column13.length() == 0)) {
			positionCacheModel.column13 = null;
		}

		positionCacheModel.column14 = getColumn14();

		String column14 = positionCacheModel.column14;

		if ((column14 != null) && (column14.length() == 0)) {
			positionCacheModel.column14 = null;
		}

		positionCacheModel.column15 = getColumn15();

		String column15 = positionCacheModel.column15;

		if ((column15 != null) && (column15.length() == 0)) {
			positionCacheModel.column15 = null;
		}

		positionCacheModel.column16 = getColumn16();

		String column16 = positionCacheModel.column16;

		if ((column16 != null) && (column16.length() == 0)) {
			positionCacheModel.column16 = null;
		}

		positionCacheModel.column17 = getColumn17();

		String column17 = positionCacheModel.column17;

		if ((column17 != null) && (column17.length() == 0)) {
			positionCacheModel.column17 = null;
		}

		positionCacheModel.column18 = getColumn18();

		String column18 = positionCacheModel.column18;

		if ((column18 != null) && (column18.length() == 0)) {
			positionCacheModel.column18 = null;
		}

		positionCacheModel.column19 = getColumn19();

		String column19 = positionCacheModel.column19;

		if ((column19 != null) && (column19.length() == 0)) {
			positionCacheModel.column19 = null;
		}

		positionCacheModel.column20 = getColumn20();

		String column20 = positionCacheModel.column20;

		if ((column20 != null) && (column20.length() == 0)) {
			positionCacheModel.column20 = null;
		}

		return positionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(45);

		sb.append("{positionID=");
		sb.append(getPositionID());
		sb.append(", headID=");
		sb.append(getHeadID());
		sb.append(", column01=");
		sb.append(getColumn01());
		sb.append(", column02=");
		sb.append(getColumn02());
		sb.append(", column03=");
		sb.append(getColumn03());
		sb.append(", column04=");
		sb.append(getColumn04());
		sb.append(", column05=");
		sb.append(getColumn05());
		sb.append(", column06=");
		sb.append(getColumn06());
		sb.append(", column07=");
		sb.append(getColumn07());
		sb.append(", column08=");
		sb.append(getColumn08());
		sb.append(", column09=");
		sb.append(getColumn09());
		sb.append(", column10=");
		sb.append(getColumn10());
		sb.append(", column11=");
		sb.append(getColumn11());
		sb.append(", column12=");
		sb.append(getColumn12());
		sb.append(", column13=");
		sb.append(getColumn13());
		sb.append(", column14=");
		sb.append(getColumn14());
		sb.append(", column15=");
		sb.append(getColumn15());
		sb.append(", column16=");
		sb.append(getColumn16());
		sb.append(", column17=");
		sb.append(getColumn17());
		sb.append(", column18=");
		sb.append(getColumn18());
		sb.append(", column19=");
		sb.append(getColumn19());
		sb.append(", column20=");
		sb.append(getColumn20());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(70);

		sb.append("<model><model-name>");
		sb.append("org.gfbio.model.Position");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>positionID</column-name><column-value><![CDATA[");
		sb.append(getPositionID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>headID</column-name><column-value><![CDATA[");
		sb.append(getHeadID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>column01</column-name><column-value><![CDATA[");
		sb.append(getColumn01());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>column02</column-name><column-value><![CDATA[");
		sb.append(getColumn02());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>column03</column-name><column-value><![CDATA[");
		sb.append(getColumn03());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>column04</column-name><column-value><![CDATA[");
		sb.append(getColumn04());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>column05</column-name><column-value><![CDATA[");
		sb.append(getColumn05());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>column06</column-name><column-value><![CDATA[");
		sb.append(getColumn06());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>column07</column-name><column-value><![CDATA[");
		sb.append(getColumn07());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>column08</column-name><column-value><![CDATA[");
		sb.append(getColumn08());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>column09</column-name><column-value><![CDATA[");
		sb.append(getColumn09());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>column10</column-name><column-value><![CDATA[");
		sb.append(getColumn10());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>column11</column-name><column-value><![CDATA[");
		sb.append(getColumn11());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>column12</column-name><column-value><![CDATA[");
		sb.append(getColumn12());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>column13</column-name><column-value><![CDATA[");
		sb.append(getColumn13());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>column14</column-name><column-value><![CDATA[");
		sb.append(getColumn14());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>column15</column-name><column-value><![CDATA[");
		sb.append(getColumn15());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>column16</column-name><column-value><![CDATA[");
		sb.append(getColumn16());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>column17</column-name><column-value><![CDATA[");
		sb.append(getColumn17());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>column18</column-name><column-value><![CDATA[");
		sb.append(getColumn18());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>column19</column-name><column-value><![CDATA[");
		sb.append(getColumn19());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>column20</column-name><column-value><![CDATA[");
		sb.append(getColumn20());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Position.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Position.class
		};
	private long _positionID;
	private long _originalPositionID;
	private boolean _setOriginalPositionID;
	private long _headID;
	private long _originalHeadID;
	private boolean _setOriginalHeadID;
	private String _column01;
	private String _column02;
	private String _column03;
	private String _column04;
	private String _column05;
	private String _column06;
	private String _column07;
	private String _column08;
	private String _column09;
	private String _column10;
	private String _column11;
	private String _column12;
	private String _column13;
	private String _column14;
	private String _column15;
	private String _column16;
	private String _column17;
	private String _column18;
	private String _column19;
	private String _column20;
	private long _columnBitmask;
	private Position _escapedModel;
}