/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.gfbio.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import org.gfbio.model.Project_User_Worker;
import org.gfbio.model.Project_User_WorkerModel;
import org.gfbio.model.Project_User_WorkerSoap;

import org.gfbio.service.persistence.Project_User_WorkerPK;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Project_User_Worker service. Represents a row in the &quot;gfbio_Project_User_Worker&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.gfbio.model.Project_User_WorkerModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Project_User_WorkerImpl}.
 * </p>
 *
 * @author froemm
 * @see Project_User_WorkerImpl
 * @see org.gfbio.model.Project_User_Worker
 * @see org.gfbio.model.Project_User_WorkerModel
 * @generated
 */
@JSON(strict = true)
public class Project_User_WorkerModelImpl extends BaseModelImpl<Project_User_Worker>
	implements Project_User_WorkerModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a project_ user_ worker model instance should use the {@link org.gfbio.model.Project_User_Worker} interface instead.
	 */
	public static final String TABLE_NAME = "gfbio_Project_User_Worker";
	public static final Object[][] TABLE_COLUMNS = {
			{ "projectID", Types.BIGINT },
			{ "userID", Types.BIGINT },
			{ "begin", Types.TIMESTAMP },
			{ "end_", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table gfbio_Project_User_Worker (projectID LONG not null,userID LONG not null,begin DATE null,end_ DATE null,primary key (projectID, userID))";
	public static final String TABLE_SQL_DROP = "drop table gfbio_Project_User_Worker";
	public static final String ORDER_BY_JPQL = " ORDER BY project_User_Worker.id.projectID ASC, project_User_Worker.id.userID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY gfbio_Project_User_Worker.projectID ASC, gfbio_Project_User_Worker.userID ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.gfbio.model.Project_User_Worker"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.gfbio.model.Project_User_Worker"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.gfbio.model.Project_User_Worker"),
			true);
	public static long PROJECTID_COLUMN_BITMASK = 1L;
	public static long USERID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Project_User_Worker toModel(Project_User_WorkerSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Project_User_Worker model = new Project_User_WorkerImpl();

		model.setProjectID(soapModel.getProjectID());
		model.setUserID(soapModel.getUserID());
		model.setBegin(soapModel.getBegin());
		model.setEnd(soapModel.getEnd());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Project_User_Worker> toModels(
		Project_User_WorkerSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Project_User_Worker> models = new ArrayList<Project_User_Worker>(soapModels.length);

		for (Project_User_WorkerSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.gfbio.model.Project_User_Worker"));

	public Project_User_WorkerModelImpl() {
	}

	@Override
	public Project_User_WorkerPK getPrimaryKey() {
		return new Project_User_WorkerPK(_projectID, _userID);
	}

	@Override
	public void setPrimaryKey(Project_User_WorkerPK primaryKey) {
		setProjectID(primaryKey.projectID);
		setUserID(primaryKey.userID);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new Project_User_WorkerPK(_projectID, _userID);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((Project_User_WorkerPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return Project_User_Worker.class;
	}

	@Override
	public String getModelClassName() {
		return Project_User_Worker.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("projectID", getProjectID());
		attributes.put("userID", getUserID());
		attributes.put("begin", getBegin());
		attributes.put("end", getEnd());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long projectID = (Long)attributes.get("projectID");

		if (projectID != null) {
			setProjectID(projectID);
		}

		Long userID = (Long)attributes.get("userID");

		if (userID != null) {
			setUserID(userID);
		}

		Date begin = (Date)attributes.get("begin");

		if (begin != null) {
			setBegin(begin);
		}

		Date end = (Date)attributes.get("end");

		if (end != null) {
			setEnd(end);
		}
	}

	@JSON
	@Override
	public long getProjectID() {
		return _projectID;
	}

	@Override
	public void setProjectID(long projectID) {
		_columnBitmask |= PROJECTID_COLUMN_BITMASK;

		if (!_setOriginalProjectID) {
			_setOriginalProjectID = true;

			_originalProjectID = _projectID;
		}

		_projectID = projectID;
	}

	public long getOriginalProjectID() {
		return _originalProjectID;
	}

	@JSON
	@Override
	public long getUserID() {
		return _userID;
	}

	@Override
	public void setUserID(long userID) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserID) {
			_setOriginalUserID = true;

			_originalUserID = _userID;
		}

		_userID = userID;
	}

	public long getOriginalUserID() {
		return _originalUserID;
	}

	@JSON
	@Override
	public Date getBegin() {
		return _begin;
	}

	@Override
	public void setBegin(Date begin) {
		_begin = begin;
	}

	@JSON
	@Override
	public Date getEnd() {
		return _end;
	}

	@Override
	public void setEnd(Date end) {
		_end = end;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public Project_User_Worker toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Project_User_Worker)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		Project_User_WorkerImpl project_User_WorkerImpl = new Project_User_WorkerImpl();

		project_User_WorkerImpl.setProjectID(getProjectID());
		project_User_WorkerImpl.setUserID(getUserID());
		project_User_WorkerImpl.setBegin(getBegin());
		project_User_WorkerImpl.setEnd(getEnd());

		project_User_WorkerImpl.resetOriginalValues();

		return project_User_WorkerImpl;
	}

	@Override
	public int compareTo(Project_User_Worker project_User_Worker) {
		Project_User_WorkerPK primaryKey = project_User_Worker.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Project_User_Worker)) {
			return false;
		}

		Project_User_Worker project_User_Worker = (Project_User_Worker)obj;

		Project_User_WorkerPK primaryKey = project_User_Worker.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		Project_User_WorkerModelImpl project_User_WorkerModelImpl = this;

		project_User_WorkerModelImpl._originalProjectID = project_User_WorkerModelImpl._projectID;

		project_User_WorkerModelImpl._setOriginalProjectID = false;

		project_User_WorkerModelImpl._originalUserID = project_User_WorkerModelImpl._userID;

		project_User_WorkerModelImpl._setOriginalUserID = false;

		project_User_WorkerModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Project_User_Worker> toCacheModel() {
		Project_User_WorkerCacheModel project_User_WorkerCacheModel = new Project_User_WorkerCacheModel();

		project_User_WorkerCacheModel.projectID = getProjectID();

		project_User_WorkerCacheModel.userID = getUserID();

		Date begin = getBegin();

		if (begin != null) {
			project_User_WorkerCacheModel.begin = begin.getTime();
		}
		else {
			project_User_WorkerCacheModel.begin = Long.MIN_VALUE;
		}

		Date end = getEnd();

		if (end != null) {
			project_User_WorkerCacheModel.end = end.getTime();
		}
		else {
			project_User_WorkerCacheModel.end = Long.MIN_VALUE;
		}

		return project_User_WorkerCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{projectID=");
		sb.append(getProjectID());
		sb.append(", userID=");
		sb.append(getUserID());
		sb.append(", begin=");
		sb.append(getBegin());
		sb.append(", end=");
		sb.append(getEnd());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("org.gfbio.model.Project_User_Worker");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>projectID</column-name><column-value><![CDATA[");
		sb.append(getProjectID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userID</column-name><column-value><![CDATA[");
		sb.append(getUserID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>begin</column-name><column-value><![CDATA[");
		sb.append(getBegin());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>end</column-name><column-value><![CDATA[");
		sb.append(getEnd());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Project_User_Worker.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Project_User_Worker.class
		};
	private long _projectID;
	private long _originalProjectID;
	private boolean _setOriginalProjectID;
	private long _userID;
	private long _originalUserID;
	private boolean _setOriginalUserID;
	private Date _begin;
	private Date _end;
	private long _columnBitmask;
	private Project_User_Worker _escapedModel;
}