/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.gfbio.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Basket_User service. Represents a row in the &quot;gfbio_Basket_User&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.gfbio.model.impl.Basket_UserModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.gfbio.model.impl.Basket_UserImpl}.
 * </p>
 *
 * @author Felicitas Loeffler
 * @see Basket_User
 * @see org.gfbio.model.impl.Basket_UserImpl
 * @see org.gfbio.model.impl.Basket_UserModelImpl
 * @generated
 */
public interface Basket_UserModel extends BaseModel<Basket_User> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a basket_ user model instance should use the {@link Basket_User} interface instead.
	 */

	/**
	 * Returns the primary key of this basket_ user.
	 *
	 * @return the primary key of this basket_ user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this basket_ user.
	 *
	 * @param primaryKey the primary key of this basket_ user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the basket i d of this basket_ user.
	 *
	 * @return the basket i d of this basket_ user
	 */
	public long getBasketID();

	/**
	 * Sets the basket i d of this basket_ user.
	 *
	 * @param basketID the basket i d of this basket_ user
	 */
	public void setBasketID(long basketID);

	/**
	 * Returns the user i d of this basket_ user.
	 *
	 * @return the user i d of this basket_ user
	 */
	public long getUserID();

	/**
	 * Sets the user i d of this basket_ user.
	 *
	 * @param userID the user i d of this basket_ user
	 */
	public void setUserID(long userID);

	/**
	 * Returns the name of this basket_ user.
	 *
	 * @return the name of this basket_ user
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this basket_ user.
	 *
	 * @param name the name of this basket_ user
	 */
	public void setName(String name);

	/**
	 * Returns the basket j s o n of this basket_ user.
	 *
	 * @return the basket j s o n of this basket_ user
	 */
	@AutoEscape
	public String getBasketJSON();

	/**
	 * Sets the basket j s o n of this basket_ user.
	 *
	 * @param basketJSON the basket j s o n of this basket_ user
	 */
	public void setBasketJSON(String basketJSON);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Basket_User basket_User);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Basket_User> toCacheModel();

	@Override
	public Basket_User toEscapedModel();

	@Override
	public Basket_User toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}