/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.gfbio.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Cell service. Represents a row in the &quot;gfbio_Cell&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.gfbio.model.impl.CellModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.gfbio.model.impl.CellImpl}.
 * </p>
 *
 * @author Marcel Froemming
 * @see Cell
 * @see org.gfbio.model.impl.CellImpl
 * @see org.gfbio.model.impl.CellModelImpl
 * @generated
 */
public interface CellModel extends BaseModel<Cell> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cell model instance should use the {@link Cell} interface instead.
	 */

	/**
	 * Returns the primary key of this cell.
	 *
	 * @return the primary key of this cell
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cell.
	 *
	 * @param primaryKey the primary key of this cell
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cell i d of this cell.
	 *
	 * @return the cell i d of this cell
	 */
	public long getCellID();

	/**
	 * Sets the cell i d of this cell.
	 *
	 * @param cellID the cell i d of this cell
	 */
	public void setCellID(long cellID);

	/**
	 * Returns the content of this cell.
	 *
	 * @return the content of this cell
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this cell.
	 *
	 * @param content the content of this cell
	 */
	public void setContent(String content);

	/**
	 * Returns the task of this cell.
	 *
	 * @return the task of this cell
	 */
	@AutoEscape
	public String getTask();

	/**
	 * Sets the task of this cell.
	 *
	 * @param task the task of this cell
	 */
	public void setTask(String task);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Cell cell);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Cell> toCacheModel();

	@Override
	public Cell toEscapedModel();

	@Override
	public Cell toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}