/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.gfbio.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import org.gfbio.service.persistence.Cell_PositionPK;

import java.io.Serializable;

/**
 * The base model interface for the Cell_Position service. Represents a row in the &quot;gfbio_Cell_Position&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.gfbio.model.impl.Cell_PositionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.gfbio.model.impl.Cell_PositionImpl}.
 * </p>
 *
 * @author Marcel Froemming
 * @see Cell_Position
 * @see org.gfbio.model.impl.Cell_PositionImpl
 * @see org.gfbio.model.impl.Cell_PositionModelImpl
 * @generated
 */
public interface Cell_PositionModel extends BaseModel<Cell_Position> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cell_ position model instance should use the {@link Cell_Position} interface instead.
	 */

	/**
	 * Returns the primary key of this cell_ position.
	 *
	 * @return the primary key of this cell_ position
	 */
	public Cell_PositionPK getPrimaryKey();

	/**
	 * Sets the primary key of this cell_ position.
	 *
	 * @param primaryKey the primary key of this cell_ position
	 */
	public void setPrimaryKey(Cell_PositionPK primaryKey);

	/**
	 * Returns the cell i d of this cell_ position.
	 *
	 * @return the cell i d of this cell_ position
	 */
	public long getCellID();

	/**
	 * Sets the cell i d of this cell_ position.
	 *
	 * @param cellID the cell i d of this cell_ position
	 */
	public void setCellID(long cellID);

	/**
	 * Returns the position i d of this cell_ position.
	 *
	 * @return the position i d of this cell_ position
	 */
	public long getPositionID();

	/**
	 * Sets the position i d of this cell_ position.
	 *
	 * @param positionID the position i d of this cell_ position
	 */
	public void setPositionID(long positionID);

	/**
	 * Returns the column of this cell_ position.
	 *
	 * @return the column of this cell_ position
	 */
	public int getColumn();

	/**
	 * Sets the column of this cell_ position.
	 *
	 * @param column the column of this cell_ position
	 */
	public void setColumn(int column);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Cell_Position cell_Position);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Cell_Position> toCacheModel();

	@Override
	public Cell_Position toEscapedModel();

	@Override
	public Cell_Position toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}