/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.gfbio.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Head service. Represents a row in the &quot;gfbio_Head&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.gfbio.model.impl.HeadModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.gfbio.model.impl.HeadImpl}.
 * </p>
 *
 * @author Marcel Froemming
 * @see Head
 * @see org.gfbio.model.impl.HeadImpl
 * @see org.gfbio.model.impl.HeadModelImpl
 * @generated
 */
public interface HeadModel extends BaseModel<Head> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a head model instance should use the {@link Head} interface instead.
	 */

	/**
	 * Returns the primary key of this head.
	 *
	 * @return the primary key of this head
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this head.
	 *
	 * @param primaryKey the primary key of this head
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the head i d of this head.
	 *
	 * @return the head i d of this head
	 */
	public long getHeadID();

	/**
	 * Sets the head i d of this head.
	 *
	 * @param headID the head i d of this head
	 */
	public void setHeadID(long headID);

	/**
	 * Returns the table_name of this head.
	 *
	 * @return the table_name of this head
	 */
	@AutoEscape
	public String getTable_name();

	/**
	 * Sets the table_name of this head.
	 *
	 * @param table_name the table_name of this head
	 */
	public void setTable_name(String table_name);

	/**
	 * Returns the table_type of this head.
	 *
	 * @return the table_type of this head
	 */
	@AutoEscape
	public String getTable_type();

	/**
	 * Sets the table_type of this head.
	 *
	 * @param table_type the table_type of this head
	 */
	public void setTable_type(String table_type);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.gfbio.model.Head head);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.gfbio.model.Head> toCacheModel();

	@Override
	public org.gfbio.model.Head toEscapedModel();

	@Override
	public org.gfbio.model.Head toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}