/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.gfbio.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import org.gfbio.model.PrimaryData_ResearchObject;
import org.gfbio.model.PrimaryData_ResearchObjectModel;
import org.gfbio.model.PrimaryData_ResearchObjectSoap;

import org.gfbio.service.persistence.PrimaryData_ResearchObjectPK;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the PrimaryData_ResearchObject service. Represents a row in the &quot;gfbio_PrimaryData_ResearchObject&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.gfbio.model.PrimaryData_ResearchObjectModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PrimaryData_ResearchObjectImpl}.
 * </p>
 *
 * @author Marcel Froemming
 * @see PrimaryData_ResearchObjectImpl
 * @see org.gfbio.model.PrimaryData_ResearchObject
 * @see org.gfbio.model.PrimaryData_ResearchObjectModel
 * @generated
 */
@JSON(strict = true)
public class PrimaryData_ResearchObjectModelImpl extends BaseModelImpl<PrimaryData_ResearchObject>
	implements PrimaryData_ResearchObjectModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a primary data_ research object model instance should use the {@link org.gfbio.model.PrimaryData_ResearchObject} interface instead.
	 */
	public static final String TABLE_NAME = "gfbio_PrimaryData_ResearchObject";
	public static final Object[][] TABLE_COLUMNS = {
			{ "primaryDataID", Types.BIGINT },
			{ "researchObjectID", Types.BIGINT },
			{ "researchObjectVersion", Types.INTEGER },
			{ "lastmodifieddate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table gfbio_PrimaryData_ResearchObject (primaryDataID LONG not null,researchObjectID LONG not null,researchObjectVersion INTEGER not null,lastmodifieddate DATE null,primary key (primaryDataID, researchObjectID, researchObjectVersion))";
	public static final String TABLE_SQL_DROP = "drop table gfbio_PrimaryData_ResearchObject";
	public static final String ORDER_BY_JPQL = " ORDER BY primaryData_ResearchObject.id.primaryDataID ASC, primaryData_ResearchObject.id.researchObjectID ASC, primaryData_ResearchObject.id.researchObjectVersion ASC";
	public static final String ORDER_BY_SQL = " ORDER BY gfbio_PrimaryData_ResearchObject.primaryDataID ASC, gfbio_PrimaryData_ResearchObject.researchObjectID ASC, gfbio_PrimaryData_ResearchObject.researchObjectVersion ASC";
	public static final String DATA_SOURCE = "gfbioDataSource";
	public static final String SESSION_FACTORY = "gfbioSessionFactory";
	public static final String TX_MANAGER = "gfbioTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.gfbio.model.PrimaryData_ResearchObject"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.gfbio.model.PrimaryData_ResearchObject"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.gfbio.model.PrimaryData_ResearchObject"),
			true);
	public static long PRIMARYDATAID_COLUMN_BITMASK = 1L;
	public static long RESEARCHOBJECTID_COLUMN_BITMASK = 2L;
	public static long RESEARCHOBJECTVERSION_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static PrimaryData_ResearchObject toModel(
		PrimaryData_ResearchObjectSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		PrimaryData_ResearchObject model = new PrimaryData_ResearchObjectImpl();

		model.setPrimaryDataID(soapModel.getPrimaryDataID());
		model.setResearchObjectID(soapModel.getResearchObjectID());
		model.setResearchObjectVersion(soapModel.getResearchObjectVersion());
		model.setLastModifiedDate(soapModel.getLastModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<PrimaryData_ResearchObject> toModels(
		PrimaryData_ResearchObjectSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<PrimaryData_ResearchObject> models = new ArrayList<PrimaryData_ResearchObject>(soapModels.length);

		for (PrimaryData_ResearchObjectSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.gfbio.model.PrimaryData_ResearchObject"));

	public PrimaryData_ResearchObjectModelImpl() {
	}

	@Override
	public PrimaryData_ResearchObjectPK getPrimaryKey() {
		return new PrimaryData_ResearchObjectPK(_primaryDataID,
			_researchObjectID, _researchObjectVersion);
	}

	@Override
	public void setPrimaryKey(PrimaryData_ResearchObjectPK primaryKey) {
		setPrimaryDataID(primaryKey.primaryDataID);
		setResearchObjectID(primaryKey.researchObjectID);
		setResearchObjectVersion(primaryKey.researchObjectVersion);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new PrimaryData_ResearchObjectPK(_primaryDataID,
			_researchObjectID, _researchObjectVersion);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((PrimaryData_ResearchObjectPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return PrimaryData_ResearchObject.class;
	}

	@Override
	public String getModelClassName() {
		return PrimaryData_ResearchObject.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("primaryDataID", getPrimaryDataID());
		attributes.put("researchObjectID", getResearchObjectID());
		attributes.put("researchObjectVersion", getResearchObjectVersion());
		attributes.put("lastModifiedDate", getLastModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long primaryDataID = (Long)attributes.get("primaryDataID");

		if (primaryDataID != null) {
			setPrimaryDataID(primaryDataID);
		}

		Long researchObjectID = (Long)attributes.get("researchObjectID");

		if (researchObjectID != null) {
			setResearchObjectID(researchObjectID);
		}

		Integer researchObjectVersion = (Integer)attributes.get(
				"researchObjectVersion");

		if (researchObjectVersion != null) {
			setResearchObjectVersion(researchObjectVersion);
		}

		Date lastModifiedDate = (Date)attributes.get("lastModifiedDate");

		if (lastModifiedDate != null) {
			setLastModifiedDate(lastModifiedDate);
		}
	}

	@JSON
	@Override
	public long getPrimaryDataID() {
		return _primaryDataID;
	}

	@Override
	public void setPrimaryDataID(long primaryDataID) {
		_columnBitmask |= PRIMARYDATAID_COLUMN_BITMASK;

		if (!_setOriginalPrimaryDataID) {
			_setOriginalPrimaryDataID = true;

			_originalPrimaryDataID = _primaryDataID;
		}

		_primaryDataID = primaryDataID;
	}

	public long getOriginalPrimaryDataID() {
		return _originalPrimaryDataID;
	}

	@JSON
	@Override
	public long getResearchObjectID() {
		return _researchObjectID;
	}

	@Override
	public void setResearchObjectID(long researchObjectID) {
		_columnBitmask |= RESEARCHOBJECTID_COLUMN_BITMASK;

		if (!_setOriginalResearchObjectID) {
			_setOriginalResearchObjectID = true;

			_originalResearchObjectID = _researchObjectID;
		}

		_researchObjectID = researchObjectID;
	}

	public long getOriginalResearchObjectID() {
		return _originalResearchObjectID;
	}

	@JSON
	@Override
	public int getResearchObjectVersion() {
		return _researchObjectVersion;
	}

	@Override
	public void setResearchObjectVersion(int researchObjectVersion) {
		_columnBitmask |= RESEARCHOBJECTVERSION_COLUMN_BITMASK;

		if (!_setOriginalResearchObjectVersion) {
			_setOriginalResearchObjectVersion = true;

			_originalResearchObjectVersion = _researchObjectVersion;
		}

		_researchObjectVersion = researchObjectVersion;
	}

	public int getOriginalResearchObjectVersion() {
		return _originalResearchObjectVersion;
	}

	@JSON
	@Override
	public Date getLastModifiedDate() {
		return _lastModifiedDate;
	}

	@Override
	public void setLastModifiedDate(Date lastModifiedDate) {
		_lastModifiedDate = lastModifiedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public PrimaryData_ResearchObject toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PrimaryData_ResearchObject)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PrimaryData_ResearchObjectImpl primaryData_ResearchObjectImpl = new PrimaryData_ResearchObjectImpl();

		primaryData_ResearchObjectImpl.setPrimaryDataID(getPrimaryDataID());
		primaryData_ResearchObjectImpl.setResearchObjectID(getResearchObjectID());
		primaryData_ResearchObjectImpl.setResearchObjectVersion(getResearchObjectVersion());
		primaryData_ResearchObjectImpl.setLastModifiedDate(getLastModifiedDate());

		primaryData_ResearchObjectImpl.resetOriginalValues();

		return primaryData_ResearchObjectImpl;
	}

	@Override
	public int compareTo(PrimaryData_ResearchObject primaryData_ResearchObject) {
		PrimaryData_ResearchObjectPK primaryKey = primaryData_ResearchObject.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PrimaryData_ResearchObject)) {
			return false;
		}

		PrimaryData_ResearchObject primaryData_ResearchObject = (PrimaryData_ResearchObject)obj;

		PrimaryData_ResearchObjectPK primaryKey = primaryData_ResearchObject.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		PrimaryData_ResearchObjectModelImpl primaryData_ResearchObjectModelImpl = this;

		primaryData_ResearchObjectModelImpl._originalPrimaryDataID = primaryData_ResearchObjectModelImpl._primaryDataID;

		primaryData_ResearchObjectModelImpl._setOriginalPrimaryDataID = false;

		primaryData_ResearchObjectModelImpl._originalResearchObjectID = primaryData_ResearchObjectModelImpl._researchObjectID;

		primaryData_ResearchObjectModelImpl._setOriginalResearchObjectID = false;

		primaryData_ResearchObjectModelImpl._originalResearchObjectVersion = primaryData_ResearchObjectModelImpl._researchObjectVersion;

		primaryData_ResearchObjectModelImpl._setOriginalResearchObjectVersion = false;

		primaryData_ResearchObjectModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<PrimaryData_ResearchObject> toCacheModel() {
		PrimaryData_ResearchObjectCacheModel primaryData_ResearchObjectCacheModel =
			new PrimaryData_ResearchObjectCacheModel();

		primaryData_ResearchObjectCacheModel.primaryDataID = getPrimaryDataID();

		primaryData_ResearchObjectCacheModel.researchObjectID = getResearchObjectID();

		primaryData_ResearchObjectCacheModel.researchObjectVersion = getResearchObjectVersion();

		Date lastModifiedDate = getLastModifiedDate();

		if (lastModifiedDate != null) {
			primaryData_ResearchObjectCacheModel.lastModifiedDate = lastModifiedDate.getTime();
		}
		else {
			primaryData_ResearchObjectCacheModel.lastModifiedDate = Long.MIN_VALUE;
		}

		return primaryData_ResearchObjectCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{primaryDataID=");
		sb.append(getPrimaryDataID());
		sb.append(", researchObjectID=");
		sb.append(getResearchObjectID());
		sb.append(", researchObjectVersion=");
		sb.append(getResearchObjectVersion());
		sb.append(", lastModifiedDate=");
		sb.append(getLastModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("org.gfbio.model.PrimaryData_ResearchObject");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>primaryDataID</column-name><column-value><![CDATA[");
		sb.append(getPrimaryDataID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>researchObjectID</column-name><column-value><![CDATA[");
		sb.append(getResearchObjectID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>researchObjectVersion</column-name><column-value><![CDATA[");
		sb.append(getResearchObjectVersion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lastModifiedDate</column-name><column-value><![CDATA[");
		sb.append(getLastModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PrimaryData_ResearchObject.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			PrimaryData_ResearchObject.class
		};
	private long _primaryDataID;
	private long _originalPrimaryDataID;
	private boolean _setOriginalPrimaryDataID;
	private long _researchObjectID;
	private long _originalResearchObjectID;
	private boolean _setOriginalResearchObjectID;
	private int _researchObjectVersion;
	private int _originalResearchObjectVersion;
	private boolean _setOriginalResearchObjectVersion;
	private Date _lastModifiedDate;
	private long _columnBitmask;
	private PrimaryData_ResearchObject _escapedModel;
}