/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.gfbio.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import org.gfbio.model.ResearchObject_User;
import org.gfbio.model.ResearchObject_UserModel;
import org.gfbio.model.ResearchObject_UserSoap;

import org.gfbio.service.persistence.ResearchObject_UserPK;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ResearchObject_User service. Represents a row in the &quot;gfbio_ResearchObject_User&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.gfbio.model.ResearchObject_UserModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ResearchObject_UserImpl}.
 * </p>
 *
 * @author Marcel Froemming
 * @see ResearchObject_UserImpl
 * @see org.gfbio.model.ResearchObject_User
 * @see org.gfbio.model.ResearchObject_UserModel
 * @generated
 */
@JSON(strict = true)
public class ResearchObject_UserModelImpl extends BaseModelImpl<ResearchObject_User>
	implements ResearchObject_UserModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a research object_ user model instance should use the {@link org.gfbio.model.ResearchObject_User} interface instead.
	 */
	public static final String TABLE_NAME = "gfbio_ResearchObject_User";
	public static final Object[][] TABLE_COLUMNS = {
			{ "researchObjectID", Types.BIGINT },
			{ "researchObjectVersion", Types.INTEGER },
			{ "userID", Types.BIGINT },
			{ "startDate", Types.TIMESTAMP },
			{ "endDate", Types.TIMESTAMP },
			{ "userType", Types.VARCHAR },
			{ "lastmodifieddate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table gfbio_ResearchObject_User (researchObjectID LONG not null,researchObjectVersion INTEGER not null,userID LONG not null,startDate DATE null,endDate DATE null,userType VARCHAR(75) null,lastmodifieddate DATE null,primary key (researchObjectID, researchObjectVersion, userID))";
	public static final String TABLE_SQL_DROP = "drop table gfbio_ResearchObject_User";
	public static final String ORDER_BY_JPQL = " ORDER BY researchObject_User.id.researchObjectID ASC, researchObject_User.id.researchObjectVersion ASC, researchObject_User.id.userID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY gfbio_ResearchObject_User.researchObjectID ASC, gfbio_ResearchObject_User.researchObjectVersion ASC, gfbio_ResearchObject_User.userID ASC";
	public static final String DATA_SOURCE = "gfbioDataSource";
	public static final String SESSION_FACTORY = "gfbioSessionFactory";
	public static final String TX_MANAGER = "gfbioTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.gfbio.model.ResearchObject_User"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.gfbio.model.ResearchObject_User"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.gfbio.model.ResearchObject_User"),
			true);
	public static long RESEARCHOBJECTID_COLUMN_BITMASK = 1L;
	public static long RESEARCHOBJECTVERSION_COLUMN_BITMASK = 2L;
	public static long USERID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ResearchObject_User toModel(ResearchObject_UserSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ResearchObject_User model = new ResearchObject_UserImpl();

		model.setResearchObjectID(soapModel.getResearchObjectID());
		model.setResearchObjectVersion(soapModel.getResearchObjectVersion());
		model.setUserID(soapModel.getUserID());
		model.setStartDate(soapModel.getStartDate());
		model.setEndDate(soapModel.getEndDate());
		model.setUserType(soapModel.getUserType());
		model.setLastModifiedDate(soapModel.getLastModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ResearchObject_User> toModels(
		ResearchObject_UserSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ResearchObject_User> models = new ArrayList<ResearchObject_User>(soapModels.length);

		for (ResearchObject_UserSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.gfbio.model.ResearchObject_User"));

	public ResearchObject_UserModelImpl() {
	}

	@Override
	public ResearchObject_UserPK getPrimaryKey() {
		return new ResearchObject_UserPK(_researchObjectID,
			_researchObjectVersion, _userID);
	}

	@Override
	public void setPrimaryKey(ResearchObject_UserPK primaryKey) {
		setResearchObjectID(primaryKey.researchObjectID);
		setResearchObjectVersion(primaryKey.researchObjectVersion);
		setUserID(primaryKey.userID);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new ResearchObject_UserPK(_researchObjectID,
			_researchObjectVersion, _userID);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((ResearchObject_UserPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return ResearchObject_User.class;
	}

	@Override
	public String getModelClassName() {
		return ResearchObject_User.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("researchObjectID", getResearchObjectID());
		attributes.put("researchObjectVersion", getResearchObjectVersion());
		attributes.put("userID", getUserID());
		attributes.put("startDate", getStartDate());
		attributes.put("endDate", getEndDate());
		attributes.put("userType", getUserType());
		attributes.put("lastModifiedDate", getLastModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long researchObjectID = (Long)attributes.get("researchObjectID");

		if (researchObjectID != null) {
			setResearchObjectID(researchObjectID);
		}

		Integer researchObjectVersion = (Integer)attributes.get(
				"researchObjectVersion");

		if (researchObjectVersion != null) {
			setResearchObjectVersion(researchObjectVersion);
		}

		Long userID = (Long)attributes.get("userID");

		if (userID != null) {
			setUserID(userID);
		}

		Date startDate = (Date)attributes.get("startDate");

		if (startDate != null) {
			setStartDate(startDate);
		}

		Date endDate = (Date)attributes.get("endDate");

		if (endDate != null) {
			setEndDate(endDate);
		}

		String userType = (String)attributes.get("userType");

		if (userType != null) {
			setUserType(userType);
		}

		Date lastModifiedDate = (Date)attributes.get("lastModifiedDate");

		if (lastModifiedDate != null) {
			setLastModifiedDate(lastModifiedDate);
		}
	}

	@JSON
	@Override
	public long getResearchObjectID() {
		return _researchObjectID;
	}

	@Override
	public void setResearchObjectID(long researchObjectID) {
		_columnBitmask |= RESEARCHOBJECTID_COLUMN_BITMASK;

		if (!_setOriginalResearchObjectID) {
			_setOriginalResearchObjectID = true;

			_originalResearchObjectID = _researchObjectID;
		}

		_researchObjectID = researchObjectID;
	}

	public long getOriginalResearchObjectID() {
		return _originalResearchObjectID;
	}

	@JSON
	@Override
	public int getResearchObjectVersion() {
		return _researchObjectVersion;
	}

	@Override
	public void setResearchObjectVersion(int researchObjectVersion) {
		_columnBitmask |= RESEARCHOBJECTVERSION_COLUMN_BITMASK;

		if (!_setOriginalResearchObjectVersion) {
			_setOriginalResearchObjectVersion = true;

			_originalResearchObjectVersion = _researchObjectVersion;
		}

		_researchObjectVersion = researchObjectVersion;
	}

	public int getOriginalResearchObjectVersion() {
		return _originalResearchObjectVersion;
	}

	@JSON
	@Override
	public long getUserID() {
		return _userID;
	}

	@Override
	public void setUserID(long userID) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserID) {
			_setOriginalUserID = true;

			_originalUserID = _userID;
		}

		_userID = userID;
	}

	public long getOriginalUserID() {
		return _originalUserID;
	}

	@JSON
	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		_startDate = startDate;
	}

	@JSON
	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		_endDate = endDate;
	}

	@JSON
	@Override
	public String getUserType() {
		if (_userType == null) {
			return StringPool.BLANK;
		}
		else {
			return _userType;
		}
	}

	@Override
	public void setUserType(String userType) {
		_userType = userType;
	}

	@JSON
	@Override
	public Date getLastModifiedDate() {
		return _lastModifiedDate;
	}

	@Override
	public void setLastModifiedDate(Date lastModifiedDate) {
		_lastModifiedDate = lastModifiedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ResearchObject_User toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ResearchObject_User)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ResearchObject_UserImpl researchObject_UserImpl = new ResearchObject_UserImpl();

		researchObject_UserImpl.setResearchObjectID(getResearchObjectID());
		researchObject_UserImpl.setResearchObjectVersion(getResearchObjectVersion());
		researchObject_UserImpl.setUserID(getUserID());
		researchObject_UserImpl.setStartDate(getStartDate());
		researchObject_UserImpl.setEndDate(getEndDate());
		researchObject_UserImpl.setUserType(getUserType());
		researchObject_UserImpl.setLastModifiedDate(getLastModifiedDate());

		researchObject_UserImpl.resetOriginalValues();

		return researchObject_UserImpl;
	}

	@Override
	public int compareTo(ResearchObject_User researchObject_User) {
		ResearchObject_UserPK primaryKey = researchObject_User.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ResearchObject_User)) {
			return false;
		}

		ResearchObject_User researchObject_User = (ResearchObject_User)obj;

		ResearchObject_UserPK primaryKey = researchObject_User.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		ResearchObject_UserModelImpl researchObject_UserModelImpl = this;

		researchObject_UserModelImpl._originalResearchObjectID = researchObject_UserModelImpl._researchObjectID;

		researchObject_UserModelImpl._setOriginalResearchObjectID = false;

		researchObject_UserModelImpl._originalResearchObjectVersion = researchObject_UserModelImpl._researchObjectVersion;

		researchObject_UserModelImpl._setOriginalResearchObjectVersion = false;

		researchObject_UserModelImpl._originalUserID = researchObject_UserModelImpl._userID;

		researchObject_UserModelImpl._setOriginalUserID = false;

		researchObject_UserModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ResearchObject_User> toCacheModel() {
		ResearchObject_UserCacheModel researchObject_UserCacheModel = new ResearchObject_UserCacheModel();

		researchObject_UserCacheModel.researchObjectID = getResearchObjectID();

		researchObject_UserCacheModel.researchObjectVersion = getResearchObjectVersion();

		researchObject_UserCacheModel.userID = getUserID();

		Date startDate = getStartDate();

		if (startDate != null) {
			researchObject_UserCacheModel.startDate = startDate.getTime();
		}
		else {
			researchObject_UserCacheModel.startDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			researchObject_UserCacheModel.endDate = endDate.getTime();
		}
		else {
			researchObject_UserCacheModel.endDate = Long.MIN_VALUE;
		}

		researchObject_UserCacheModel.userType = getUserType();

		String userType = researchObject_UserCacheModel.userType;

		if ((userType != null) && (userType.length() == 0)) {
			researchObject_UserCacheModel.userType = null;
		}

		Date lastModifiedDate = getLastModifiedDate();

		if (lastModifiedDate != null) {
			researchObject_UserCacheModel.lastModifiedDate = lastModifiedDate.getTime();
		}
		else {
			researchObject_UserCacheModel.lastModifiedDate = Long.MIN_VALUE;
		}

		return researchObject_UserCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{researchObjectID=");
		sb.append(getResearchObjectID());
		sb.append(", researchObjectVersion=");
		sb.append(getResearchObjectVersion());
		sb.append(", userID=");
		sb.append(getUserID());
		sb.append(", startDate=");
		sb.append(getStartDate());
		sb.append(", endDate=");
		sb.append(getEndDate());
		sb.append(", userType=");
		sb.append(getUserType());
		sb.append(", lastModifiedDate=");
		sb.append(getLastModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("org.gfbio.model.ResearchObject_User");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>researchObjectID</column-name><column-value><![CDATA[");
		sb.append(getResearchObjectID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>researchObjectVersion</column-name><column-value><![CDATA[");
		sb.append(getResearchObjectVersion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userID</column-name><column-value><![CDATA[");
		sb.append(getUserID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>startDate</column-name><column-value><![CDATA[");
		sb.append(getStartDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endDate</column-name><column-value><![CDATA[");
		sb.append(getEndDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userType</column-name><column-value><![CDATA[");
		sb.append(getUserType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lastModifiedDate</column-name><column-value><![CDATA[");
		sb.append(getLastModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ResearchObject_User.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ResearchObject_User.class
		};
	private long _researchObjectID;
	private long _originalResearchObjectID;
	private boolean _setOriginalResearchObjectID;
	private int _researchObjectVersion;
	private int _originalResearchObjectVersion;
	private boolean _setOriginalResearchObjectVersion;
	private long _userID;
	private long _originalUserID;
	private boolean _setOriginalUserID;
	private Date _startDate;
	private Date _endDate;
	private String _userType;
	private Date _lastModifiedDate;
	private long _columnBitmask;
	private ResearchObject_User _escapedModel;
}