/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.gfbio.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Content service. Represents a row in the &quot;gfbio_Content&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.gfbio.model.impl.ContentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.gfbio.model.impl.ContentImpl}.
 * </p>
 *
 * @author Marcel Froemming
 * @see Content
 * @see org.gfbio.model.impl.ContentImpl
 * @see org.gfbio.model.impl.ContentModelImpl
 * @generated
 */
public interface ContentModel extends BaseModel<Content> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a content model instance should use the {@link Content} interface instead.
	 */

	/**
	 * Returns the primary key of this content.
	 *
	 * @return the primary key of this content
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this content.
	 *
	 * @param primaryKey the primary key of this content
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the content i d of this content.
	 *
	 * @return the content i d of this content
	 */
	public long getContentID();

	/**
	 * Sets the content i d of this content.
	 *
	 * @param contentID the content i d of this content
	 */
	public void setContentID(long contentID);

	/**
	 * Returns the head i d of this content.
	 *
	 * @return the head i d of this content
	 */
	public long getHeadID();

	/**
	 * Sets the head i d of this content.
	 *
	 * @param headID the head i d of this content
	 */
	public void setHeadID(long headID);

	/**
	 * Returns the column i d of this content.
	 *
	 * @return the column i d of this content
	 */
	public long getColumnID();

	/**
	 * Sets the column i d of this content.
	 *
	 * @param columnID the column i d of this content
	 */
	public void setColumnID(long columnID);

	/**
	 * Returns the row i d of this content.
	 *
	 * @return the row i d of this content
	 */
	public long getRowID();

	/**
	 * Sets the row i d of this content.
	 *
	 * @param rowID the row i d of this content
	 */
	public void setRowID(long rowID);

	/**
	 * Returns the cell content of this content.
	 *
	 * @return the cell content of this content
	 */
	@AutoEscape
	public String getCellContent();

	/**
	 * Sets the cell content of this content.
	 *
	 * @param cellContent the cell content of this content
	 */
	public void setCellContent(String cellContent);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.gfbio.model.Content content);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.gfbio.model.Content> toCacheModel();

	@Override
	public org.gfbio.model.Content toEscapedModel();

	@Override
	public org.gfbio.model.Content toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}