/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.gfbio.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import org.gfbio.service.persistence.DataProvider_PersistentIdentifierPK;

import java.io.Serializable;

/**
 * The base model interface for the DataProvider_PersistentIdentifier service. Represents a row in the &quot;gfbio_DataProvider_PersistentIdentifier&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.gfbio.model.impl.DataProvider_PersistentIdentifierModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.gfbio.model.impl.DataProvider_PersistentIdentifierImpl}.
 * </p>
 *
 * @author Marcel Froemming
 * @see DataProvider_PersistentIdentifier
 * @see org.gfbio.model.impl.DataProvider_PersistentIdentifierImpl
 * @see org.gfbio.model.impl.DataProvider_PersistentIdentifierModelImpl
 * @generated
 */
public interface DataProvider_PersistentIdentifierModel extends BaseModel<DataProvider_PersistentIdentifier> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a data provider_ persistent identifier model instance should use the {@link DataProvider_PersistentIdentifier} interface instead.
	 */

	/**
	 * Returns the primary key of this data provider_ persistent identifier.
	 *
	 * @return the primary key of this data provider_ persistent identifier
	 */
	public DataProvider_PersistentIdentifierPK getPrimaryKey();

	/**
	 * Sets the primary key of this data provider_ persistent identifier.
	 *
	 * @param primaryKey the primary key of this data provider_ persistent identifier
	 */
	public void setPrimaryKey(DataProvider_PersistentIdentifierPK primaryKey);

	/**
	 * Returns the gfbio data provider of this data provider_ persistent identifier.
	 *
	 * @return the gfbio data provider of this data provider_ persistent identifier
	 */
	public long getGfbioDataProvider();

	/**
	 * Sets the gfbio data provider of this data provider_ persistent identifier.
	 *
	 * @param gfbioDataProvider the gfbio data provider of this data provider_ persistent identifier
	 */
	public void setGfbioDataProvider(long gfbioDataProvider);

	/**
	 * Returns the gfbio persistent identifier of this data provider_ persistent identifier.
	 *
	 * @return the gfbio persistent identifier of this data provider_ persistent identifier
	 */
	public long getGfbioPersistentIdentifier();

	/**
	 * Sets the gfbio persistent identifier of this data provider_ persistent identifier.
	 *
	 * @param gfbioPersistentIdentifier the gfbio persistent identifier of this data provider_ persistent identifier
	 */
	public void setGfbioPersistentIdentifier(long gfbioPersistentIdentifier);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.gfbio.model.DataProvider_PersistentIdentifier dataProvider_PersistentIdentifier);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.gfbio.model.DataProvider_PersistentIdentifier> toCacheModel();

	@Override
	public org.gfbio.model.DataProvider_PersistentIdentifier toEscapedModel();

	@Override
	public org.gfbio.model.DataProvider_PersistentIdentifier toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}