/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.gfbio.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import org.gfbio.service.persistence.Funding_InstitutionProjectPK;

import java.io.Serializable;

/**
 * The base model interface for the Funding_InstitutionProject service. Represents a row in the &quot;gfbio_Funding_InstitutionProject&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.gfbio.model.impl.Funding_InstitutionProjectModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.gfbio.model.impl.Funding_InstitutionProjectImpl}.
 * </p>
 *
 * @author Marcel Froemming
 * @see Funding_InstitutionProject
 * @see org.gfbio.model.impl.Funding_InstitutionProjectImpl
 * @see org.gfbio.model.impl.Funding_InstitutionProjectModelImpl
 * @generated
 */
public interface Funding_InstitutionProjectModel extends BaseModel<Funding_InstitutionProject> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a funding_ institution project model instance should use the {@link Funding_InstitutionProject} interface instead.
	 */

	/**
	 * Returns the primary key of this funding_ institution project.
	 *
	 * @return the primary key of this funding_ institution project
	 */
	public Funding_InstitutionProjectPK getPrimaryKey();

	/**
	 * Sets the primary key of this funding_ institution project.
	 *
	 * @param primaryKey the primary key of this funding_ institution project
	 */
	public void setPrimaryKey(Funding_InstitutionProjectPK primaryKey);

	/**
	 * Returns the project i d of this funding_ institution project.
	 *
	 * @return the project i d of this funding_ institution project
	 */
	public long getProjectID();

	/**
	 * Sets the project i d of this funding_ institution project.
	 *
	 * @param projectID the project i d of this funding_ institution project
	 */
	public void setProjectID(long projectID);

	/**
	 * Returns the funding agency i d of this funding_ institution project.
	 *
	 * @return the funding agency i d of this funding_ institution project
	 */
	public long getFundingAgencyID();

	/**
	 * Sets the funding agency i d of this funding_ institution project.
	 *
	 * @param fundingAgencyID the funding agency i d of this funding_ institution project
	 */
	public void setFundingAgencyID(long fundingAgencyID);

	/**
	 * Returns the funding program i d of this funding_ institution project.
	 *
	 * @return the funding program i d of this funding_ institution project
	 */
	public long getFundingProgramID();

	/**
	 * Sets the funding program i d of this funding_ institution project.
	 *
	 * @param fundingProgramID the funding program i d of this funding_ institution project
	 */
	public void setFundingProgramID(long fundingProgramID);

	/**
	 * Returns the institution i d of this funding_ institution project.
	 *
	 * @return the institution i d of this funding_ institution project
	 */
	public long getInstitutionID();

	/**
	 * Sets the institution i d of this funding_ institution project.
	 *
	 * @param institutionID the institution i d of this funding_ institution project
	 */
	public void setInstitutionID(long institutionID);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.gfbio.model.Funding_InstitutionProject funding_InstitutionProject);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.gfbio.model.Funding_InstitutionProject> toCacheModel();

	@Override
	public org.gfbio.model.Funding_InstitutionProject toEscapedModel();

	@Override
	public org.gfbio.model.Funding_InstitutionProject toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}