/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.gfbio.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import org.gfbio.service.persistence.Funding_PersonProjectPK;

import java.io.Serializable;

/**
 * The base model interface for the Funding_PersonProject service. Represents a row in the &quot;gfbio_Funding_PersonProject&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.gfbio.model.impl.Funding_PersonProjectModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.gfbio.model.impl.Funding_PersonProjectImpl}.
 * </p>
 *
 * @author Marcel Froemming
 * @see Funding_PersonProject
 * @see org.gfbio.model.impl.Funding_PersonProjectImpl
 * @see org.gfbio.model.impl.Funding_PersonProjectModelImpl
 * @generated
 */
public interface Funding_PersonProjectModel extends BaseModel<Funding_PersonProject> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a funding_ person project model instance should use the {@link Funding_PersonProject} interface instead.
	 */

	/**
	 * Returns the primary key of this funding_ person project.
	 *
	 * @return the primary key of this funding_ person project
	 */
	public Funding_PersonProjectPK getPrimaryKey();

	/**
	 * Sets the primary key of this funding_ person project.
	 *
	 * @param primaryKey the primary key of this funding_ person project
	 */
	public void setPrimaryKey(Funding_PersonProjectPK primaryKey);

	/**
	 * Returns the project i d of this funding_ person project.
	 *
	 * @return the project i d of this funding_ person project
	 */
	public long getProjectID();

	/**
	 * Sets the project i d of this funding_ person project.
	 *
	 * @param projectID the project i d of this funding_ person project
	 */
	public void setProjectID(long projectID);

	/**
	 * Returns the funding agency i d of this funding_ person project.
	 *
	 * @return the funding agency i d of this funding_ person project
	 */
	public long getFundingAgencyID();

	/**
	 * Sets the funding agency i d of this funding_ person project.
	 *
	 * @param fundingAgencyID the funding agency i d of this funding_ person project
	 */
	public void setFundingAgencyID(long fundingAgencyID);

	/**
	 * Returns the funding program i d of this funding_ person project.
	 *
	 * @return the funding program i d of this funding_ person project
	 */
	public long getFundingProgramID();

	/**
	 * Sets the funding program i d of this funding_ person project.
	 *
	 * @param fundingProgramID the funding program i d of this funding_ person project
	 */
	public void setFundingProgramID(long fundingProgramID);

	/**
	 * Returns the person i d of this funding_ person project.
	 *
	 * @return the person i d of this funding_ person project
	 */
	public long getPersonID();

	/**
	 * Sets the person i d of this funding_ person project.
	 *
	 * @param personID the person i d of this funding_ person project
	 */
	public void setPersonID(long personID);

	/**
	 * Returns the person type of this funding_ person project.
	 *
	 * @return the person type of this funding_ person project
	 */
	@AutoEscape
	public String getPersonType();

	/**
	 * Sets the person type of this funding_ person project.
	 *
	 * @param personType the person type of this funding_ person project
	 */
	public void setPersonType(String personType);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.gfbio.model.Funding_PersonProject funding_PersonProject);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.gfbio.model.Funding_PersonProject> toCacheModel();

	@Override
	public org.gfbio.model.Funding_PersonProject toEscapedModel();

	@Override
	public org.gfbio.model.Funding_PersonProject toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}