/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.gfbio.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Search_History service. Represents a row in the &quot;gfbio_Search_History&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.gfbio.model.impl.Search_HistoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.gfbio.model.impl.Search_HistoryImpl}.
 * </p>
 *
 * @author Marcel Froemming
 * @see Search_History
 * @see org.gfbio.model.impl.Search_HistoryImpl
 * @see org.gfbio.model.impl.Search_HistoryModelImpl
 * @generated
 */
public interface Search_HistoryModel extends BaseModel<Search_History> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a search_ history model instance should use the {@link Search_History} interface instead.
	 */

	/**
	 * Returns the primary key of this search_ history.
	 *
	 * @return the primary key of this search_ history
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this search_ history.
	 *
	 * @param primaryKey the primary key of this search_ history
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the search history i d of this search_ history.
	 *
	 * @return the search history i d of this search_ history
	 */
	public long getSearchHistoryID();

	/**
	 * Sets the search history i d of this search_ history.
	 *
	 * @param searchHistoryID the search history i d of this search_ history
	 */
	public void setSearchHistoryID(long searchHistoryID);

	/**
	 * Returns the user i d of this search_ history.
	 *
	 * @return the user i d of this search_ history
	 */
	public long getUserID();

	/**
	 * Sets the user i d of this search_ history.
	 *
	 * @param userID the user i d of this search_ history
	 */
	public void setUserID(long userID);

	/**
	 * Returns the query string of this search_ history.
	 *
	 * @return the query string of this search_ history
	 */
	@AutoEscape
	public String getQueryString();

	/**
	 * Sets the query string of this search_ history.
	 *
	 * @param queryString the query string of this search_ history
	 */
	public void setQueryString(String queryString);

	/**
	 * Returns the last modified date of this search_ history.
	 *
	 * @return the last modified date of this search_ history
	 */
	public Date getLastModifiedDate();

	/**
	 * Sets the last modified date of this search_ history.
	 *
	 * @param lastModifiedDate the last modified date of this search_ history
	 */
	public void setLastModifiedDate(Date lastModifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.gfbio.model.Search_History search_History);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.gfbio.model.Search_History> toCacheModel();

	@Override
	public org.gfbio.model.Search_History toEscapedModel();

	@Override
	public org.gfbio.model.Search_History toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}