/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.gfbio.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the User_SSO service. Represents a row in the &quot;gfbio_User_SSO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.gfbio.model.impl.User_SSOModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.gfbio.model.impl.User_SSOImpl}.
 * </p>
 *
 * @author Marcel Froemming
 * @see User_SSO
 * @see org.gfbio.model.impl.User_SSOImpl
 * @see org.gfbio.model.impl.User_SSOModelImpl
 * @generated
 */
public interface User_SSOModel extends BaseModel<User_SSO> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user_ s s o model instance should use the {@link User_SSO} interface instead.
	 */

	/**
	 * Returns the primary key of this user_ s s o.
	 *
	 * @return the primary key of this user_ s s o
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user_ s s o.
	 *
	 * @param primaryKey the primary key of this user_ s s o
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user i d of this user_ s s o.
	 *
	 * @return the user i d of this user_ s s o
	 */
	public long getUserID();

	/**
	 * Sets the user i d of this user_ s s o.
	 *
	 * @param userID the user i d of this user_ s s o
	 */
	public void setUserID(long userID);

	/**
	 * Returns the token of this user_ s s o.
	 *
	 * @return the token of this user_ s s o
	 */
	@AutoEscape
	public String getToken();

	/**
	 * Sets the token of this user_ s s o.
	 *
	 * @param token the token of this user_ s s o
	 */
	public void setToken(String token);

	/**
	 * Returns the last modified date of this user_ s s o.
	 *
	 * @return the last modified date of this user_ s s o
	 */
	public Date getLastModifiedDate();

	/**
	 * Sets the last modified date of this user_ s s o.
	 *
	 * @param lastModifiedDate the last modified date of this user_ s s o
	 */
	public void setLastModifiedDate(Date lastModifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.gfbio.model.User_SSO user_SSO);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.gfbio.model.User_SSO> toCacheModel();

	@Override
	public org.gfbio.model.User_SSO toEscapedModel();

	@Override
	public org.gfbio.model.User_SSO toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}